### ISSUE TITLE
Wrong line endings (CRCRLF) in the output win+py27

### ISSUE THREAD

**Issue by atugushev** [pallets/click#1231] opened 2019-02-16 12:27 UTC
Click generates output with `\r\r\n` line endings. I've prepared a test to demonstrate it. See PR #1232 and failed jobs on [appveyour](https://ci.appveyor.com/project/pallets/click/builds/22420449).

##### Environment Versions

1. OS Type: Windows
1. Python version: 2.7
1. click version:  7.0

##### Steps to replicate

1. Prepare testfile.py

```
cat << EOF > testfile.py
import click

@click.command()
@click.option('--foo', help='bar')
def cli(foo):
    click.echo(foo)

if __name__ == '__main__':
    cli()
EOF
```

2. `python testfile.py --help`

##### Expected result

Expecting `\r\n` line endings.

```
Usage: testfile.py [OPTIONS]

Options:
  --foo TEXT  bar
  --help      Show this message and exit.
```

##### Actual result

Got `\r\r\n` line endings.

```
Usage: testfile.py [OPTIONS]


Options:

  --foo TEXT  bar

  --help      Show this message and exit.

```

**Comment by davidism** [comment] 2020-02-24 01:15
Can't reproduce this with the linked failing test. May have been fixed as part of 7.1, which will be released soon.

**Closed by davidism** 2020-02-24 01:15 UTC
Labels: bug
