### ISSUE TITLE
Support common groups of options shared between multiple commands

### ISSUE THREAD

**Issue by davebirch** [pallets/click#1726] opened 2020-12-01 12:18 UTC
Our team is currently having a play with click to see if we can replace our current command parsing code. We have a number of cases in our code where we have a set of options which is shared between multiple commands, but which we don't want to add as a separate level of subcommands.

Ideally we would like to have these defined once, then composed into our click commands as a group, with the return of the option group being a namespace object containing the options defined.

a rough stab at the api would be something like this:
```
@click.option_group()
@click.option("--foo")
@click.option("--bar")
def baz_group(foo, bar):
    pass

@click.group()
def base():
    pass

@base.command()
@baz_group.options()
def command1(baz_group):
    click.echo(baz_group.foo)

@base.command()
@baz_group.options()
def command2(baz_group)
   click.echo(baz_group.bar)

@base.command()
@click.option("--other")
def command3(other):
    click.echo(other)
```

I can't see that this kind of decorated, composable group structure if available via any existing click functionality. I have managed to get something like it working by defining click.options in a callback, then adding the parameters to the command for this option, but this then means that if a change is made to the callback, the person making the change needs to remember to add the parameter to each place that callback is used, which seem less than ideal.

Preferably, it would be nice to be able to define a function, with a set of options and variables, then compose these options into a command under a namespace

e.g
```
def baz_group(function) -> Any:
    function = click.option('--foo')(function)
    function = click.option('--bar')(function)
    return function

@click.command()
@baz_group
def command1(foo, bar):
    click.echo(foo)
    click.echo(bar)
```

**Comment by davidism** [comment] 2020-12-01 17:27
> Preferably, it would be nice to be able to define a function, with a set of options and variables, then compose these options into a command under a namespace

That's already possible, no extra support in Click required.

Basically a duplicate of #1104 and many others. Use a decorator to apply a common set of options to multiple commands, or add the options to the group and pass them on through `ctx.obj`.

**Closed by davidism** 2020-12-01 17:27 UTC
