### ISSUE TITLE
should_strip_ansi cannot be user controlled

### ISSUE THREAD

**Issue by ssbarnea** [pallets/click#1713] opened 2020-11-18 11:56 UTC
There are particular use cases where the user wants to enforce a particular ANSI behavior, like enforcing use of ANSI or the opposite enforcing the ANSI avoidance.

At this moment click internal logic does not allow any click library user to override its logic, and this produces some bugs.

https://github.com/pallets/click/blob/97de2c97275f52adc5c6ef8bb8aa993ce997fe7e/src/click/_compat.py#L487
That is the code that makes the decision and whatever logic we put into it we will never be able to be 100% sure that that is what the user really wanted.

I already have an example of similar function but one that allows user to override behavior via external environment variables. See https://github.com/ansible-community/molecule/blob/master/src/molecule/console.py#L40-L60

### Expected Behavior

Be able to enforce use of ANSI, or the opposite, bypassing the detection logic.
```
CLICOLOR=1 some-cli-using-click > result.out
```

### Actual Behavior

`some-cli-using-click > result.out` will always strip ANSI and there is no way to force it to do so.

When using CI systems you do not usually have a terminal so click will decide to strip ansi, even if the system supports ANSI.

In fact current implementation from  https://github.com/pallets/click/blob/97de2c97275f52adc5c6ef8bb8aa993ce997fe7e/src/click/_compat.py#L491 does disable ANSI for any non interactive console, which does break in all automation cases, where `stdin` not interactive.

### Environment

* Python version: any
* Click version: 7.1.2

Please note that I would gladly propose a PR to address this after getting some feedback from the core team regarding which implementation approach they would prefer.

**Comment by ssbarnea** [comment] 2020-11-18 12:01
I do have another use case that is mainly broken by this: if a Python application is replacing the standard streams with a FileProxy in order to capture them, it will also break click ability to determine if it should use ANSI or not.

**Comment by davidism** [comment] 2020-11-18 14:29
Duplicate of #1498

**Closed by davidism** 2020-11-18 14:29 UTC
