### ISSUE TITLE
api.html page is missing from the online documentation

### ISSUE THREAD

**Issue by asweigart** [pallets/click#1541] opened 2020-04-27 07:45 UTC
The api.html page for the online documentation at https://click.palletsprojects.com/en/7.x/api.html is missing. I discovered this by searching for the echo() function in the sidebar's search bar, and followed a link which ended with a 404.

I'm not sure if other pages are also missing as well, but I haven't found any.

**Comment by davidism** [comment] 2020-04-27 13:48
Duplicate of #1513. It's a bug with a combination of Sphinx version and RTD behavior which I'm working with RTD to fix.

**Closed by davidism** 2020-04-27 13:48 UTC
