### ISSUE TITLE
Custom type called twice with prompt

### ISSUE THREAD

**Issue by FBruzzesi** [pallets/click#2735] opened 2024-05-28 21:16 UTC
# Description

**Disclaimer**: I hope this is the right place in which to ask and report this.

While working with a [Typer](https://typer.tiangolo.com/) CLI application, I encountered the following issue: when using prompt with custom type, the type casting fires twice, _only_ if the value is inserted via the prompt.

@lachaib helped me point it down to click behavior.

I would expect this not to happen, or to figure out if there is another way to do this.

## Minimal reproducible example

**t.py**
```py
import click

class Token:
    def __init__(self, token: str):
        print(f"Creating API client with token '{token}'")
        self._token = token

@click.command()
@click.option("--token", prompt="Insert secret token", type=click.types.FuncParamType(Token))
def ping(token: Token):
    print(f"Ping GitHub with token {token._token}")

if __name__ == "__main__":
    ping()
```

If `token` is passed as argument, the behaviour is as expected:

```bash
$ python t.py --token secret
```

```terminal
Creating API client with token 'secret'
Ping GitHub with token secret
```

On the other hand, when `token` is passed via prompt, then type conversion fires twice:

```bash
python t.py
```

```terminal
Insert secret token: secret

Creating API client with token 'secret'
Creating API client with token '<__main__.Token object at 0x7f07138c4af0>'
Ping GitHub with token <__main__.Token object at 0x7f07138c4af0>
```

## Environment

- Python version: 3.10.12
- Click version: 8.1.7

**Comment by davidism** [comment] 2024-05-28 22:28
Duplicate of https://github.com/pallets/click/issues/2662
Duplicate of https://github.com/pallets/click/issues/2259

This is due to how the processing pipeline works. Since the value wasn't given, it's prompted for. The prompt calls the callback to ensure the user typed a valid value before continuing (otherwise it keeps prompting). Then the value continues through the processing pipeline, which calls the callback (regardless of source) to validate the option before passing it to the command.

**Closed by davidism** 2024-05-28 22:28 UTC

**Comment by lachaib** [comment] 2024-05-29 05:36
Hello @davidism , just my 2 cents here: you're mentioning this issue as duplicate of 2 others, which means that several developers ended up with a use case of using a callback & prompt, while your answer consistently is "known behaviour". Wouldn't be a great idea to add a warning or so in the documentation so that we spend less time trying to get a clue on what's going on?
