### ISSUE TITLE
Click helptext fails at parsing click.Choice types

### ISSUE THREAD

**Issue by jcastagneri** [pallets/click#1765] opened 2021-01-29 17:54 UTC
## Versions
Python version: 3.8.6 (also seen on 3.7.3 and 3.6.8)
Click version: 7.1.2

## Summary of problem
Helptext generation fails when there is a `click.Choice` present. It doesn't affect runtime, just helptext.

## Existing issues
I don't believe this is a duplicate based on my quick search. I have replicated this on the most recent version of `click` released to `pypi`.

## Expected result
With my example below, I expect to see helptext that tells me about my `click.Choice` option.

## Minimum example
I have a minimal click project set up using `poetry` to isolate dependencies. Below is my `pyproject.toml`:
```
[tool.poetry]
name = "test-poetry-failure"
version = "0.1.0"
description = ""
authors = ["Joe Castagneri <joe@amprobotics.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

I have a trivial python project set up:
```
.
├── poetry.lock
├── pyproject.toml
└── test_poetry_failure
    ├── __init__.py
```

The contents of `__init__.py` are:
```
import click


@click.command()
@click.option('-f', '--float-choice', type=click.Choice([1.0, 1.1]), default=1.0)
def main_cli(float_choice: float):
    print('Hello world')
    print(float_choice)


if __name__ == '__main__':
    main_cli()

```

Running this script works as expected:
```
 ❯ poetry run python test_poetry_failure/__init__.py
Hello world
1.0
```

However, if you try to print the helptext, there is a type checking error:
```
 ❯ poetry run python test_poetry_failure/__init__.py --help

Traceback (most recent call last):
  File "test_poetry_failure/__init__.py", line 12, in <module>
    main_cli()
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 950, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 570, in get_help
    return self.command.get_help(self)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 975, in get_help
    self.format_help(ctx, formatter)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 1003, in format_help
    self.format_options(ctx, formatter)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 1024, in format_options
    rv = param.get_help_record(ctx)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 1868, in get_help_record
    rv = [_write_opts(self.opts)]
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 1865, in _write_opts
    rv += " {}".format(self.make_metavar())
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/core.py", line 1520, in make_metavar
    metavar = self.type.get_metavar(self)
  File "/home/joe/.cache/pypoetry/virtualenvs/test-poetry-failure-SIkJq1Oe-py3.8/lib/python3.8/site-packages/click/types.py", line 161, in get_metavar
    return "[{}]".format("|".join(self.choices))
TypeError: sequence item 0: expected str instance, float found
```

In my debugger, the `types.py` file is passed my entire choice array as a string (e.g. as `"[1.0, 1.1]"`) which I believe is the cause of the issue here.

**Comment by davidism** [comment] 2021-01-29 18:06
Choices must be strings, this is called out in the docs: https://click.palletsprojects.com/en/7.x/api/#click.Choice Notice what happens if you try to do `python example.py -f 1.0`.

Duplicate of #591, see https://github.com/pallets/click/issues/591#issuecomment-673179242 and https://github.com/pallets/click/pull/1395#issuecomment-673178527 for decision.

**Closed by davidism** 2021-01-29 18:06 UTC
