### ISSUE TITLE
Callback not called when value passed as environment variable

### ISSUE THREAD

**Issue by fretboarder** [pallets/click#1562] opened 2020-05-26 17:42 UTC
### Expected Behavior

The following snipped takes 2 numbers and calculates a random number, very simple.

```python
from random import randint

def validate_lower(ctx, params, value):
    return value

def validate_upper(ctx, params, value):
    if value < ctx.params['lower']: 
        raise click.BadParameter("{} is invalid".format(value))
    return value

@click.command()
@click.option('--lower', required=True, type=int, callback=validate_lower)
@click.option('--upper', required=True, type=int, callback=validate_upper)
def random(lower, upper):
    click.echo(randint(lower, upper))


if __name__ == "__main__":
    random(auto_envvar_prefix='CLI')
```

Of course this works perfectly when the options are passed on the command line, e.g. `python random.py --lower 1 --upper 10`. The validate_upper() function just wants to check if the upper value is greather than the lower value.

### Actual Behavior

Validation callback function seems not to be called if the first parameter is provided as environment variable. In the context object passed to validate_upper() there's no entry for 'lower' as it would be expected.
 
```pytb
export CLI_LOWER=1
python random.py --upper 10

  ...
  File "mlnctl.py", line 607, in validate_upper
    if value < ctx.params['lower']: 
KeyError: 'lower'
```

Am I doing something wrong here? Or why is the validate_lower() function not called?

### Environment

* Python version: 3.7
* Click version: 7.1.2

**Comment by IamCathal** [comment] 2020-06-16 14:47
Reproduced the error and I'm looking into this at the moment

**Comment by IamCathal** [comment] 2020-06-17 17:37
Hi, I'm currently working on this issue but I'm not quite at the point yet where I can write up a solution and know it won't break everything. You are right in thinking that if no `--lower` option is provided then the callback is not invoked for that argument.

In the mean time I came up with this quick fix. Instead of checking if the lower value is in the params you can instead check if the `lower` env var is set and then go from there.

If you didn't have to put all the logic in the callbacks you could reduce a good bit of the checking that I've done in my quick fix.

Run this before:
`export lower=3`
```python
import click
import os
from random import randint

def validate_lower(ctx, params, value):
    if 'lower' not in os.environ:
        # There is no env var set,
        # take from the value given
        ctx.params['lower'] = int(value)
        return int(value)
    else:
        # if env var is set but value
        # explicitly given, use that
        if value is not None:
            return int(value)
        else:
            return int(os.environ['lower'])

def validate_upper(ctx, params, value):
    if 'lower' in os.environ:
        if value < int(os.environ['lower']):  
            raise click.BadParameter("{} is invalid".format(value))
        else:
            return int(value)
    else:
        # The env var is not set, check the value given
        if 'lower' in ctx.params:
            if value < ctx.params['lower']:
                raise click.BadParameter("{} is invalid".format(value))
        else:
            # If the env and no value were set, then for now
            # I dont have a solution since you'd need to compare against
            # the default value of lower
            return int(value)

@click.command()
@click.option('--lower', type=int, callback=validate_lower,
                default=10,
                envvar='lower')
@click.option('--upper', required=True,type=int,
                default=15,
                callback=validate_upper)
def random(lower, upper):
    click.echo(f"Args: {lower}:{upper}")
    click.echo(f"Answer: {randint(lower, upper)}")


if __name__ == "__main__":
    random()
```

**Comment by parabolize** [comment] 2020-08-29 23:10
I'm not sure its a bug in click. You are comparing one option to another which requires the other option to be added to Context.params first. Your program also fails when `upper` is before `lower`:
```
python random.py --upper 10 --lower 1
```
One solution is to set `lower` option to `is_eager=True` see [https://click.palletsprojects.com/en/7.x/options/#callbacks-and-eager-options](url)

Another solution is to compare the options in the command:
```python
import click
import random


@click.command(context_settings={'auto_envvar_prefix': 'CLI'})
@click.option('-l', '--lower',
        required=True, type=int)
@click.option('-u', '--upper',
        required=True, type=int)
def run(lower, upper):
    if lower >= upper:
        er = f'lower:{lower} is not lower then upper:{upper}'
        raise click.BadParameter(er)
    click.echo(random.randint(lower, upper))
```

**Comment by jcrotts** [comment] 2020-08-30 06:25
Going to close this, because I don't think this is an issue with click. Thanks @parabolize and @IamCathal for looking into this and providing work arounds.

**Closed by jcrotts** 2020-08-30 06:25 UTC
