### ISSUE TITLE
RuntimeError when env variable LANG is set to anything except for en

### ISSUE THREAD

**Issue by sio13** [pallets/click#1967] opened 2021-06-22 09:45 UTC
When the env variable LANG is set to 'de', the autocompletion activation is causing RuntimeError.
```
  File "/Users/martingano/repos/esp-idf/tools/idf.py", line 740, in main
    cli(sys.argv[1:], prog_name=PROG, complete_var='_IDF.PY_COMPLETE')
  File "/Users/martingano/.espressif/python_env/idf4.4_py3.7_env/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/martingano/.espressif/python_env/idf4.4_py3.7_env/lib/python3.7/site-packages/click/core.py", line 1057, in main
    self._main_shell_completion(extra, prog_name, complete_var)
  File "/Users/martingano/.espressif/python_env/idf4.4_py3.7_env/lib/python3.7/site-packages/click/core.py", line 1132, in _main_shell_completion
    rv = shell_complete(self, ctx_args, prog_name, complete_var, instruction)
  File "/Users/martingano/.espressif/python_env/idf4.4_py3.7_env/lib/python3.7/site-packages/click/shell_completion.py", line 45, in shell_complete
    echo(comp.source())
  File "/Users/martingano/.espressif/python_env/idf4.4_py3.7_env/lib/python3.7/site-packages/click/shell_completion.py", line 324, in source
    self._check_version()
  File "/Users/martingano/.espressif/python_env/idf4.4_py3.7_env/lib/python3.7/site-packages/click/shell_completion.py", line 320, in _check_version
    _("Couldn't detect Bash version, shell completion is not supported.")
RuntimeError: Couldn't detect Bash version, shell completion is not supported.

```

Steps:
1. `export LANG=de`
2. source this script `eval "$(env LANG=en _IDF.PY_COMPLETE=$SOURCE_BASH idf.py)"`

Expected behavior should be activation of autocomplete feature.
The actual behavior is RuntimeError.

Please, consider merging this PR https://github.com/pallets/click/pull/1968

Environment:

- Python version: 3.7.8
- Click version: 8.0.1

**Comment by davidism** [comment] 2021-06-22 13:25
Duplicate of #1940

**Closed by davidism** 2021-06-22 13:25 UTC
