### ISSUE TITLE
Handle restructured text in command help text

### ISSUE THREAD

**Issue by danchr** [pallets/click#1208] opened 2019-01-21 10:49 UTC
The formatter doesn't handle restructured text in the help text all that gracefully. Given that it's the standard within the Python ecosystem, and used by tools such as [sphinx-click](https://sphinx-click.readthedocs.io/en/latest/), it would be nice to have a way to handle it. Ideally, you'd get fully formatted output on UNIX terminals, but not breaking up the output would be a good start.

In particular, the current formatter doesn't handle literal blocks and itemised lists all that well.

**Comment by davidism** [comment] 2019-01-21 14:06
Duplicate of #561 
Possible fix in #938 
Related to #255

**Closed by davidism** 2019-01-21 14:06 UTC
