### ISSUE TITLE
documentation broken redirects

### ISSUE THREAD

**Issue by ssbarnea** [pallets/click#1544] opened 2020-04-29 10:24 UTC
Try to load https://click.palletsprojects.com/en/7.x/api.html?highlight=group#click.group which is the first suggestion when searching for "group" on https://click.palletsprojects.com/en/7.x/search/?q=group

What you will endup with is an endless redirect:
![](https://sbarnea.com/ss/Screen-Shot-2020-04-29-11-23-41.92.png)

**Comment by davidism** [comment] 2020-04-29 12:17
Duplicate of #1513

**Closed by davidism** 2020-04-29 12:17 UTC
