### ISSUE TITLE
Cannot show help documentation for subcommand without giving required optional flags

### ISSUE THREAD

**Issue by mikebentley15** [pallets/click#2073] opened 2021-09-23 06:03 UTC
# Description

Click is all about subcommands, much like how the `git` command-line interface is built.  Each subcommand will have its own help documentation.  That can be very helpful.

However, if the base command has some required optional parameters, then you cannot query `--help` on subcommands without providing those required optional parameters.

Here is a minimal example to illustrate my point:

**File:** `example.py`

```{python}
import click

@click.group()
@click.option("--required", required=True, type=click.STRING)
def cli(required):
    # do something with required
    pass

@cli.command()
@click.argument("filepath", type=click.File("r"), required=True)
def sub(filepath):
    # do something with filepath
    pass

if __name__ == "__main__":
    cli()
```

Now, from the terminal:

```
$ python example.py --help
Usage: example.py [OPTIONS] COMMAND [ARGS]...

Options:
  --required TEXT  [required]
  --help           Show this message and exit.

Commands:
  sub
```

but for the subcommand

```
$ python example.py sub --help
Usage: example.py [OPTIONS] COMMAND [ARGS]...
Try 'example.py --help' for help.

Error: Missing option '--required'.
```

Is this really the intended behavior?  When asking for `--help`, even for a subcommand, why would any flags, arguments, or parameters be required?

I haven't checked to see if this is the case for other types of parameters, flags, or options on the top-level command.

I would expect the following output:

```
$ python example.py sub --help
Usage: example.py sub [OPTIONS] FILEPATH

Options:
  --help  Show this message and exit.
```

although arguably some information about the arguments to the top-level command might be good to be displayed here.

I understand even in this case, the base command function is called and executed.  Why?  Should it be when all we do is ask for help documentation?

# Environment:

- Python version: 3.9.6
- Click version: 8.0.1

**Comment by davidism** [comment] 2021-10-06 00:33
Duplicate of #295, #814, etc.

**Closed by davidism** 2021-10-06 00:33 UTC
