### ISSUE TITLE
Add feature to disable any impact on std streams

### ISSUE THREAD

**Issue by lukjak** [pallets/click#2573] opened 2023-07-25 08:35 UTC
The feature should disable any processing done by click with regard to std streams. If required for technical reasons, it can also totally disable click functions which interact with them, like echo.

This feature would solve issues with wrapped packages/functions using own std stream handling, like pytest. Using logging under pytest wrapped in click results in unresolvable exceptions (using any click functions for output is not an option here).

Also, disabling of unnecceessary functionality would make click much more obvious and easy to use.

**Comment by davidism** [comment] 2023-07-25 12:29
Click itself doesn't modify `sys.stdout` etc., only the test runner does. The test runner isn't required to run tests, `command.main()` takes `standalone_mode=False` to run without exiting. Also, duplicate of multiple currently open issues in this issue tracker, please remember to search before opening a new issue.

**Closed by davidism** 2023-07-25 12:29 UTC

**Comment by lukjak** [comment] 2023-07-25 12:42
This is completely not my situation - I have pytest stuff _wrapped_ in a click command line. And I get "OSError [WinError 6] The handle is invalid" from click.core on exit once I do the wrapping.

OK, I guess I just need to dump click.
