### ISSUE TITLE
Allow showing `--help` without arguments

### ISSUE THREAD

**Issue by cool-RR** [pallets/click#492] opened 2015-12-17 15:19 UTC
When someone invokes my CLI without arguments, I want him to see the same help screen he'd get if he specified `--help`. I wish there was an argument to the `command` decorator that did that.

**Comment by nchammas** [comment] 2015-12-21 03:00
You mean show help for a *subcommand* when invoked without arguments? Because I see that Click already shows help if you invoke the top-level application without any arguments.

**Comment by cool-RR** [comment] 2015-12-21 10:17
I meant the top level, not a subcommand. I remember seeing Click shows some
help but not all the stuff you see with `--help`

**Comment by nchammas** [comment] 2015-12-21 15:32
Please be more specific. I see the same output when I invoke the top level app without arguments and when I invoke it with `--help`.

**Comment by cool-RR** [comment] 2015-12-21 15:43
When I launch the script with `--help`, I get the "usage" line, the
docstring, and the list of options.

When I launch the script without `--help`, I get the "usage" line and an
error message about the first argument being empty. (Error message
generated by my own code.)

**Comment by untitaker** [comment] 2016-04-08 20:30
Potential duplicate of https://github.com/pallets/click/issues/499

**Closed** 2016-04-08 20:30 UTC
