### ISSUE TITLE
Options with unknown numbers of arguments

### ISSUE THREAD

**Issue by BastG57** [pallets/click#1818] opened 2021-03-22 10:19 UTC
Hi,

I would like to use an option with an unknown number of arguments following, like in this example command where "-s" is the option :
` myscript -s 10 11 21 5 -k id`

But I see click isn't providing such an option, the only way seems to use the @click.argument() decorator with nargs=-1 and having the click.option() as a boolean :
 ```
@step.command()
@click.option( '-k', default=0, required=True)
@click.option('-s', required=True, is_flag=True)
@click.argument('stepIDs, nargs=-1)
```

Problem is by doing it this way the help doc is that clear about the usage. The arguments are considered as general commands arguments and not "-s" option's arguments
I'm also aware of the multiple=True parameter, but I find it very inconvenient to repaeat -s 10 -s 11 -s 21 -s 5..... as my users could have many -s args to write.

Why couldnt we simply implement it like this ?
`@click.option('-step', required=True, default=0, nargs=-1)`

Thank you

**Comment by davidism** [comment] 2021-03-22 17:57
Duplicate of #1658

This isn't possible to do unambiguously. You could use a custom type, such as accepting one quoted argument, like `-s "a b c d"` and splitting it.

**Closed by davidism** 2021-03-22 17:57 UTC
