### ISSUE TITLE
stdout is not wrapped

### ISSUE THREAD

**Issue by nowox** [pallets/click#694] opened 2016-12-01 11:05 UTC
With this example: 

```
#!/usr/bin/env python
import click

@click.command()
def main():
    line = ">" + ("*" * 500)
    print(line)
    click.echo(line)

if __name__ == '__main__':
    main()
```

I get this output where my line is not wrapped (so I cannot see all of it): 

```
$ tput cols
42
$ ./toto.py
>*****************************************
>*****************************************
```

I am rather expecting this: 

```
./toto.py
>********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
```

Is it a normal behavior?

**Comment by untitaker** [comment] 2016-12-01 12:34
I cannot reproduce this, `tput cols` has no effect. Have you tried another terminal?

**Comment by nowox** [comment] 2016-12-01 13:23
So it's a terminal dependent issue :( I am on Cygwin/[mintty](https://github.com/mintty/mintty)). 

I haven't tried it on another terminal. 

What could possibly be the cause of this issue?

**Comment by untitaker** [comment] 2016-12-01 13:28
You should try another terminal, or check if this issue occurs with other programs as well.

However, I'm going to close this because I don't think this is an issue with Click.

**Closed by untitaker** 2016-12-01 13:28 UTC
