### ISSUE TITLE
click.Path cannot handle filenames like '[1-0].suffix'

### ISSUE THREAD

**Issue by hinerk** [pallets/click#2080] opened 2021-10-01 09:51 UTC
`click.Path` seems to interpret file names like `something_[2021-01-26][09-25-32].html`. The issue can be boiled down to `[1-0]` which will raise a `re.error: bad character range 1-0 at position 5`.

 - the issue occurs on Windows
 - the issue doesn't occur on Linux

Please consider the following example:

```python
import click


@click.command()
@click.argument('file', type=click.Path())
def hello(file):
    click.echo(f'Hello world, hello {file}')


if __name__ == '__main__':
    # for the sake of simplicity: append the file name right here instead of
    # providing it via command line. It provokes the same result!
    import sys
    sys.argv.append('[1-0]')

    hello()
```

While, like mentioned, there is no issue executing this example on Linux, running on Windows leaves the following trace:

```
(venv) [1] ***> python click_test.py '[1-0]'
Traceback (most recent call last):
  File "C:\Users\***\development\click_test\click_test.py", line 9, in <module>
    hello()
  File "C:\Users\***\development\click_test\venv\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\***\development\click_test\venv\lib\site-packages\click\core.py", line 1049, in main
    args = _expand_args(args)
  File "C:\Users\***\development\click_test\venv\lib\site-packages\click\utils.py", line 572, in _expand_args
    matches = glob(arg, recursive=glob_recursive)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\glob.py", line 22, in glob
    return list(iglob(pathname, recursive=recursive))
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\glob.py", line 58, in _iglob
    yield from _glob1(dirname, basename, dironly)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\glob.py", line 86, in _glob1
    return fnmatch.filter(names, pattern)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\fnmatch.py", line 58, in filter
    match = _compile_pattern(pat)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\fnmatch.py", line 52, in _compile_pattern
    return re.compile(res).match
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\re.py", line 252, in compile
    return _compile(pattern, flags)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range 1-0 at position 5
```

Even though I am not happy with those file names either, I would expect `click.Path` to deal with it anyway.

Environment:

- Python version: 3.9.7
- Click version: 8.0.1

**Comment by hinerk** [comment] 2021-10-01 10:09
**it is about arguments in general - not only `click.Path`!**

I was pretty convinced I could address my issue by avoiding to specify the type of the argument. Turns out, this issue is not only about `click.Path`. The error persist after removing the `type` argument. See the example:

```python
import click


@click.command()
@click.argument('file')
def hello(file):
    click.echo(f'Hello world, hello {file}')


if __name__ == '__main__':
    # for the sake of simplicity: append the file name right here instead of
    # providing it via command line. It provokes the same result!
    import sys
    sys.argv.append('[1-0]')

    hello()
```

is causing the same issue!

**Comment by hinerk** [comment] 2021-10-01 10:16
both examples works using click 7.1.2

**Comment by davidism** [comment] 2021-10-01 13:25
Duplicate of #1918

**Closed by davidism** 2021-10-01 13:25 UTC
