### ISSUE TITLE
Question, display choices on argument

### ISSUE THREAD

**Issue by joveice** [pallets/click#1080] opened 2018-07-31 08:33 UTC
so I have a argument

```
@click.argument('type', type=click.Choice(['raw', 'list']))
```

do a --help and I get this
```
Usage: script.py display list [OPTIONS] TYPE COMMAND [ARGS]

    short help description

Options:
    --help: ...
```

How can I get something like this?
```
Usage: script.py display list [ raw | list ]

    short help description

Options:
    --help: ...
```
or 
```
Usage: script.py display list [OPTIONS] TYPE COMMAND [ARGS]

    positional arguments:
        {raw, list}

    short help description

Options:
    --help: ...
```

Awesome package!

**Comment by davidism** [comment] 2018-07-31 13:17
Basically a duplicate of #1051. You should document the arguments in the docstring, Click will not do that for you.

**Closed by davidism** 2018-07-31 13:17 UTC
