### ISSUE TITLE
Official support and or documentation for auto discovery of (sub-)commands.

### ISSUE THREAD

**Issue by tback** [pallets/click#2318] opened 2022-07-06 15:18 UTC
Support and documentation for auto discovery of (sub-)commands.
I'd like to be able start a  ToolboxCLI in just a few lines of code.

I'd like official support for a toolbox scenario: Developer teams tend to create tool collections over time. Those collections tend to get messy because they lack a convention (language, documentation, argument parsing, online help) how to implement commands. I've seen teams working on django applications collecting their toolbox in management commands and not facing this challenge.
I'd like something that is close to django management commands, but based on click. And without django obviously. I think it's a common usage scenario for click that is currently harder to implement than needs to be.

My current solution looks somewhat like this. I had to delete and rename some stuff and I didn't run this anonymized code. It's most obvious shortcoming is that it doesn't show global options on the subcommand help page.

```python
#toolbox_cli.py
import pathlib
import click
import os
import typing


class ToolboxCLI(click.MultiCommand):
    commands_folder = pathlib.Path.joinpath(
        pathlib.Path(__file__).parent, "commands"
    ).resolve()

    def list_commands(self, ctx: click.Context) -> typing.List[str]:
        rv = []
        for filename in os.listdir(self.commands_folder):
            if filename.endswith(".py") and not filename.startswith("__init__"):
                rv.append(filename[:-3])
        rv.sort()
        return rv

    def get_command(
        self, ctx: click.Context, cmd_name: str
    ) -> typing.Optional[click.Command]:
        ns = {}
        fn = pathlib.Path.joinpath(self.commands_folder, cmd_name + ".py")
        with open(fn) as f:
            code = compile(f.read(), fn, "exec")
            eval(code, ns, ns)
        return ns["cli"]

#__init__.py
@click.group(
    cls=ToolboxCLI,
    context_settings={
        "allow_interspersed_args": True,
    },
)
@click.option(
    "--log-level",
    #...
    help="Set log level.",
)
def cli(log_level):
    """Toolbox CLI"""

#commands/admin.py
@click.group()
def cli():
    pass


@cli.command()
def create_admin():
    pass

@cli.command()
def delete_admin():
    pass
```

**Comment by davidism** [comment] 2022-07-06 15:25
In terms of documenting the general idea of overriding `get_command` and `list_commands`, that's a duplicate of https://github.com/pallets/click/issues/945.

The actual feature request here is too broad for me to be comfortable maintaining a general solution in Click itself. Perhaps that's a good idea for an extension package.

**Closed by davidism** 2022-07-06 15:25 UTC

**Comment by tback** [comment] 2022-07-07 08:04
Thanks @davidism. Unfortunately I don't think I can make the time to build and publish the extension. 
Do you (or anyone) know of any projects that implemented such a use case in click?
