### ISSUE TITLE
prompt(hide_input=True) broken on Windows

### ISSUE THREAD

**Issue by matejcik** [pallets/click#2021] opened 2021-07-28 13:37 UTC
`click.prompt(hide_input=True)` defers to `getpass`, which has been [broken on Windows](https://bugs.python.org/issue44762) for quite some time (i'm finding complaints from 2011).

The problem is that on Windows, `getpass` always assumes it's running in a terminal and uses terminal functions to read input. This effectively freezes the program if it's not actually running in a terminal.
Notably, this happens in MinTTY which is the terminal used by Git Bash and several other popular programs.

---

To reproduce:

- install Git for Windows without winpty support (which was only added recently)
- use the following test script:
  ```
  import click

  print(click.prompt("say something", hide_input=True))
  ```
- run this script from inside Git Bash
- whatever you type to the "say something" prompt is shown on terminal, and the program never accepts the input

---

This is of course not a bug in Click but in getpass. However, perhaps Click is a good place to fix it, e.g., by checking if `sys.stdin.isatty()` and falling back to non-hidden prompt or something.

**Comment by davidism** [comment] 2021-07-28 14:13
> falling back to non-hidden prompt or something

We rely on `getpass` to get hidden input securely. I know getpass itself does this by calling `fallback_getpass`, but I'm not confident about doing the same manually from Click. If the issue is fixed in getpass then we're suddenly less secure than it. If there's a bug in getpass, MinTTY, or Git for Windows, it needs to be fixed in the appropriate place.

I do have a general refactoring goal of allowing a project to override functions such as `prompt`, so it may become possible in the future for a project to choose to use an insecure function.

**Closed** 2021-08-14 12:31 UTC
