### ISSUE TITLE
Not specifying a group's command exits with code 0

### ISSUE THREAD

**Issue by plannigan** [pallets/click#1486] opened 2020-03-05 16:51 UTC
When a group is created with multiple commands, but the script is called without any commands, the exit code is 0. It looks like [this line](https://github.com/pallets/click/blob/466d0add86f48502db9c02c32e30287d39ab866b/click/core.py#L1028) just needs to be changed to have an exit code. But it's not clear if `ctx.fail()` should be used instead.

### Example Code

```python
import click

@click.group()
def cli():
    print("in group")

@cli.command()
def foo():
    print("foo")

@cli.command()
def bar():
    print("bar")

if __name__ == "__main__":
    print("before group")
    cli()
```

### Expected Behavior

A non-zero exit code.

### Actual Behavior

```shell
$ python click_poc.py 
before group
Usage: click_poc.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  bar
  foo
$ echo $?
0
```

### Environment

* Python version: Python 3.8.0
* Click version: Click==7.0

**Comment by fdavis** [comment] 2020-03-06 22:37
it looks like ctx.fail will also dump a stacktrace but I think most users would expect this case to print usage and return non-zero.
I made a PR to just add an exit code 1 to that line here: https://github.com/pallets/click/pull/1489

**Comment by davidism** [comment] 2020-08-13 16:21
Duplicate of #1394

**Closed by davidism** 2020-08-13 16:21 UTC
