### ISSUE TITLE
is there any way of grouping about command

### ISSUE THREAD

**Issue by deadlylaid** [pallets/click#984] opened 2018-05-03 05:46 UTC
```

@click.group(invoke_without_command=True)
@click.pass_context
def cli(ctx):
    if ctx.invoked_subcommand is None:
        _search_all()
    else:
        pass


@cli.command()
def name():
    _name()


@cli.command()
def age():
    _age()


def _search_all():
    _name()
    _age()


def _name():
    print("name")


def _age():
    print("age")
```

```
$ cli
>>> name
>>> age

$ cli name
>>> name

$ cli age
>>> age
```

but I want add argument in cli command like

```
$ cli mike 26
>>> mike
>>> 26

$ cli name mike
>>> mike

$ cli age 26
>>> 26
```

but when I run ```cli name mike``` , **name** is recognized argument,,,

so, i wonder if it is possible.

**Comment by dawran6** [comment] 2018-05-13 21:42
It might not be possible since it is ambiguous for click (and for the user) to determine whether the first argument is a argument or a subcommand, i.e., which of the following usage should be like?

1. `Usage: issue_984.py [OPTIONS] ARG_NAME ARG_AGE COMMAND`, or
1. `Usage: issue_984.py [OPTIONS] COMMAND`

I'd suggest to use option instead of the argument based on the context I got. For example:

```python
import click

@click.group(invoke_without_command=True)
@click.pass_context
@click.option('--name')
@click.option('--age')
def cli(ctx, name, age):
    if ctx.invoked_subcommand is None:
        print(f'--name: {name}')
        print(f'--age: {age}')
    else:
        pass

@cli.command()
@click.argument('arg')
def name(arg):
    print(f'got arg: {arg}')

@cli.command()
@click.argument('arg')
def age(arg):
    print(f'got arg: {arg}')

if __name__ == '__main__':
    cli()
```

This way you get similarly:

```
$ cli --name mike --age 26
--name: mike
--age: 26

$ cli name mike
got arg: mike

$ cli age 26
got arg: 26
```

This way you can still safely pass in the `--name` and `--age` options.
The values pass in to the option will be ignored in this case.

Do you think this solves your problem?

**Comment by dawran6** [comment] 2018-05-14 13:31
@davidism (or other maintainer) would you close this issue for now? We could reopen it if the issue isn't resolved. Thanks.

**Closed** 2018-05-14 14:10 UTC
