### ISSUE TITLE
Prompt fails with nargs

### ISSUE THREAD

**Issue by dipkakwani** [pallets/click#578] opened 2016-05-08 18:18 UTC
`@click.option('--sign', prompt=True, nargs=2, type=int, help='signature of the message')`
When I don't give the option in command line, the prompt appears like this:
`Sign [()]:`
And it doesn't take 2 integers, instead it gives an error.
`Sign [()]: 1 2`
`Error:   is not a valid integer`
How do I take two integers input from prompt? It seems I also can't use type=(int, int) instead of nargs.

**Comment by z123** [comment] 2016-05-18 04:33
This seems like a bug. For now you should just take the value as a string and parse it yourself. In the code it seems like this type of input isn't accounted for at all. I can put in a pull request to fix this, but I am unsure what the intended behavior should be.

**Comment by fdavis** [comment] 2018-05-15 19:59
closing in favor of https://github.com/pallets/click/issues/532

**Closed by fdavis** 2018-05-15 19:59 UTC
Labels: duplicate
