### ISSUE TITLE
Progress bar does not display until after the first item is complete

### ISSUE THREAD

**Issue by max-sixty** [pallets/click#1648] opened 2020-08-16 23:46 UTC
Take this example:
```python
    with click.progressbar(length=6, label="Doing something") as bar:
        for thing in [3, 2, 1]:
            time.sleep(thing)
            bar.update(thing)
```

This shows nothing until three seconds, at which point it shows:
```
Doing something  [##################------------------]   50%  00:00:03
```

Would it be reasonable for it to display a `0%` at first? 
This is mostly an issue with a small number of items which take a long time.

**Comment by davidism** [comment] 2020-08-16 23:56
Duplicate of #1353.

**Comment by max-sixty** [comment] 2020-08-17 02:28
I saw that issue – fine if you prefer to group them. It's not necessarily the same issue though: would be possible to display the last item _and_ start showing from the 0th item.

**Comment by davidism** [comment] 2021-03-04 00:47
This was introduced in #487. I just ran into the same confusion when fixing the tests for #1353/#1354, the first line of progress wasn't shown and it wasn't clear why. Reading #487, I'm not convinced by the reasoning, if you have a fast machine or fast process, it doesn't hurt to output the progress bar. I'm going to revert that.

*Maybe* it would make sense to somehow hide the progress bar if *all* iterations finish quickly, but otherwise you end up in this weird situation where the bar displays late because the first iteration is always "fast". I don't see a simple way to implement that though, and in general want to avoid adding complexity to Click's progress bar at this point.

**Closed** 2021-03-04 02:34 UTC
Labels: f:progress bar
