### ISSUE TITLE
click.Choice() doesn't like integers while getting --help

### ISSUE THREAD

**Issue by jsmedmar** [pallets/click#784] opened 2017-05-10 15:42 UTC
click.Choice() doesn't like integers while getting --help.

Given:
```
click.option(
    "--pk",
    type=click.Choice([1, 2, 3]),
    help="Select the primary key.",
    default=1
    )
```

Gives:
```
 803, in show_help
    echo(ctx.get_help(), color=ctx.color)   
  File "{...}/lib/python3.5/site-packages/click/core.py", line 495, in get_help
    return self.command.get_help(self)
  File "{...}/lib/python3.5/site-packages/click/core.py", line 824, in get_help
    self.format_help(ctx, formatter)
  File "{...}/lib/python3.5/site-packages/click/core.py", line 839, in format_help
    self.format_options(ctx, formatter)
  File "{...}/lib/python3.5/site-packages/click/core.py", line 853, in format_options
    rv = param.get_help_record(ctx)
  File "{...}/lib/python3.5/site-packages/click/core.py", line 1602, in get_help_record
    rv = [_write_opts(self.opts)]
  File "{...}/lib/python3.5/site-packages/click/core.py", line 1599, in _write_opts
    rv += ' ' + self.make_metavar()
  File "{...}/lib/python3.5/site-packages/click/core.py", line 1292, in make_metavar
    metavar = self.type.get_metavar(self)   
  File "{...}/lib/python3.5/site-packages/click/types.py", line 140, in get_metavar
    return '[%s]' % '|'.join(self.choices)  
TypeError: sequence item 0: expected str instance, int found
````

**Comment by prusnak** [comment] 2017-07-12 13:58
Just hit that issue as well.

Seems that most of the functions of `class Choice` are expecting `choices` as list of strings, but I guess there is no reason why we should not be able to use ints instead.

I am workarounding the issue by using list of strings though and than calling int(foo) when working with the passed value.

**Comment by d-ganchar** [comment] 2018-05-18 05:43
@prusnak , @fdavis are you sure that this is bug?
To fix it need to change `.join(self.choices)` to `.join([str(i) for i in self.choices])` [here](https://github.com/pallets/click/blob/master/click/types.py#L147), [here](https://github.com/pallets/click/blob/master/click/types.py#L150) and [here](https://github.com/pallets/click/blob/master/click/types.py#L178). But we will have a new problem. List of choices is **integer**, but we will get value as **string** from command line. So this means that validation will never be successful(because **'1' != 1**). 
I think you can describe choices as strings and convert type inside command if you need. What do you think?

```
@cli.command()
@click.option("--pk",
    type=click.Choice(['1', '2', '3']),
    help="Select the primary key.",
    default='1')
def test(pk):
    do_something(int(pk))
```

**Comment by prusnak** [comment] 2018-05-18 10:58
@d-ganchar Probably not a bug per se, but totally not following the Principle of least surprise.

I know it's possible to create a new Choice type ([example|https://github.com/trezor/python-trezor/blob/master/trezorctl#L40-L65]), but I think passing ints is quite common, so this might deserve a special treatment. Maybe creating a click.ChoiceInt type?

**Comment by d-ganchar** [comment] 2018-05-18 11:31
@prusnak I think that your decision makes sense

**Comment by fdavis** [comment] 2018-05-18 23:19
While docstring on `class Choice` says that [choices must be a string](https://github.com/pallets/click/blob/master/click/types.py#L128-L130) I agree with @prusnak that its surprising and at the very least we should just enforce the type self.choices in `__init__` so it doesn't fail elsewhere

**Comment by IKOBH** [comment] 2018-10-29 07:43
Was this issue resolved?

**Comment by jcrotts** [comment] 2019-05-07 17:05
We are happy to review PRs on this, but I feel that adding a click.ChoiceInt type or similar will add unnecessary complication to the API. 

The user is going to be inputting strings from the command line, so I think the default of specifying a choice as a list of strings makes sense.

I am going to close this for now, but feel free to open if someone has an implementation or a PR.

**Closed by jcrotts** 2019-05-07 17:05 UTC
Labels: bug
