### ISSUE TITLE
Expand all defaults in to sys.argv like variable

### ISSUE THREAD

**Issue by keiranmraine** [pallets/click#1972] opened 2021-06-23 08:18 UTC
Produce an array similar to `sys.argv` but with any unspecified params completed with default values.  Include option for `long-names` (fall back to short if option doesn't have long name).

Allows the full details of a programs invocation to be easily added to output file headers.

**Comment by davidism** [comment] 2021-06-23 13:36
Duplicate of #1279

**Closed by davidism** 2021-06-23 13:36 UTC
