### ISSUE TITLE
take defaults and types from keyword arguments

### ISSUE THREAD

**Issue by tmbdev** [pallets/click#1466] opened 2020-02-06 17:08 UTC
Consider the following little program:

```Python
import click                                                                    
                                                                                
@click.command()                                                                
#@click.option("--arg")  #(1)                                                       
@click.option("--arg", default=17)  #(2)
def command(arg=19):                                                            
    print(arg, type(arg))                                                       
                                                                                
if __name__=='__main__':                                                        
    command()   
```

Here, if using declaration (1), passing an argument with `--arg` will result in the passing of a string argument. On the other hand, declaration (2) overrides the default and forces the programmer to repeat defaults.

It would seem to be nicer behavior if `@click.option` used reflection to get the default value from keyword arguments, removing the need for duplication of the default and avoiding potential type inconsistencies.

(Perhaps to avoid backwards incompatibility where people rely on the odd current behavior, the fix could use a slight variant, say, `@click.opt`. When used with `default=`, it would just behave as the current options.)

```Python
import click                                                                    
                                                                                
@click.command()
@click.opt("--arg", help="defaults to '19' of type 'int'")
def command(arg=19):
    print(arg, type(arg))
     
if __name__=='__main__':
    command()
```

**Comment by davidism** [comment] 2020-02-06 19:43
Thanks for the suggestion. This is essentially a duplicate of #1456, replacing introspecting annotations with introspecting defaults. We don't plan to add this at this time.

**Closed by davidism** 2020-02-06 19:43 UTC

**Comment by tmbdev** [comment] 2020-02-09 18:25
#1456 suggests using Python3-specific type annotations. I'm suggesting something much simpler: when no "default=" argument is given to @click.option, just use the default value from the argspec and continue as before:

    # inside @click.option
    if default is None:
        sig = inspect.signature(f)
        if option_name in sig:
            default = sig.parameters.[option_name].value
    # continue as before
