### ISSUE TITLE
Make Click arguments "pipeable"

### ISSUE THREAD

**Issue by arredond** [pallets/click#1202] opened 2019-01-08 12:07 UTC
To use Click program's in a truly UNIX fashion, it would be nice to have an option to make an argument "pipeable", that is, so that it can be provided via a pipe **as well as explicitly** in the standard positional sense.

I've achieved this previously using a custom function (which is fully based on [this Stackoverflow answer](https://stackoverflow.com/a/45845513/8159847):

```python
def check_piped_arg(ctx, param, value):
    if value:
        return value
    else:
        if not sys.stdin.isatty():
            return sys.stdin.read().rstrip()
        else:
            ctx.fail(
                f"Missing argument: {param.human_readable_name}.\n"
                "Either pass it explicitly or pipe into the command"
            )
```

This function can then be simply used in the `callback` argument of the `@click.argument` decorator. However, this has some caveats:

- The `@click.argument` must be set to `required=False`, which is pretty counter-intuitive, since the argument _is_ provided, just that in a different position.
- A new fail message must be written, instead of providing the standard error when an argument is missing.

Having the option to directly make arguments "pipeable" would definitely be nice (Click could just use this same behaviour under the hood) and would invite users to do it at a higher level. Something like:

```python
@click.argument('arg_name', pipeable=True)
```

Of course, some issues (like having multiple arguments) would have to be taken into account (only allow one "pipeable" argument per sub-command, for example?)

What do you think?

**Comment by davidism** [comment] 2019-01-08 13:18
Duplicate of #1144

**Closed by davidism** 2019-01-08 13:18 UTC

**Comment by arredond** [comment] 2019-01-08 14:11
Sorry to insist on this but I think it's clear there is some interest in such a feature being implemented in Click, both by the existence of both issues and also the SO question.

If I may ask, why do you argue in the other issue (posted by @tedivm) that:

> This doesn't seem like an appropriate use of pipes.

This is exactly the use that's given in many other common UNIX tools such as `head`, `grep`, etc, which are for many the archetype of command line tools.

**Comment by tedivm** [comment] 2019-01-08 22:48
Agreed- it's obvious people want this, so it seems reasonable to at least leave the issue open for discussion.

I also never understood why it wasn't an appropriate use for pipes.
