### ISSUE TITLE
Workaround for pipeable arguments

### ISSUE THREAD

**Issue by taranlu-houzz** [pallets/click#1616] opened 2020-06-30 18:23 UTC
I realize this has been addressed before in #1202 and #1144. I'd like to throw in a possible workaround, since allowing for basic pipe usage seems like something that should be a fundamental part of any Unix tool IMO. I feel like something like this could be really useful as a quick setting/option:

```python
#!/usr/bin/env python3

"""my_tool.py
"""

import sys

import click


# Gather data from stdin in case using a pipe
if not sys.stdin.isatty():
    sys.argv += sys.stdin.read().split()


@click.command()
@click.argument("arg_1")
def cli(arg_1):
    print(arg_1)


if __name__ == "__main__":
    cli()
```

I'm guessing that there are probably drawbacks that I am not aware of, but so far, this works for me for implementing basic piping functionality.

### Expected Behavior

I feel like it should be possible to do this:
```sh
> echo "test" | my_tool
test

>
```

### Actual Behavior

Trying to do this without the `sys.stdin.isatty` workaround results in:
```sh
Error: Missing argument 'ARG_1'.
```

### Environment

* Python version: 3.7.7
* Click version: 7.1.2

**Comment by davidism** [comment] 2020-06-30 18:36
Duplicate of #1144 

I definitely don't think the proposed workaround is safe to have Click do automatically.

Again, this seems like a very specific use case: "I have a program that takes exactly one argument, and it should take that from stdin". There's nothing in Click preventing a project that needs this from doing what you've shown, or subclassing `Argument` as I suggested in the first issue.

**Closed by davidism** 2020-06-30 18:36 UTC

**Comment by taranlu-houzz** [comment] 2020-06-30 18:59
Fair enough. Thank you for the response.
