### ISSUE TITLE
Lazy `echo_via_pager`

### ISSUE THREAD

**Issue by macobo** [pallets/click#281] opened 2015-01-16 19:46 UTC
When outputting tens of thousands of lines of text via a pager, formatting it all at once might take a lot of time.

This cost can be hidden from the user by being lazy and only formatting the first few lines of output when the pager is called.The rest is generated on demand either as the user scrolls down or in a separate thread.

**Comment by fdavis** [comment] 2018-05-15 15:13
Duplicate of #449 
Closed by #889 

Please reopen if this is a still an issue

**Closed by fdavis** 2018-05-15 15:13 UTC
Labels: enhancement
