### ISSUE TITLE
Ignore/pass over the double dash (--) marker

### ISSUE THREAD

**Issue by Higgcz** [pallets/click#1340] opened 2019-06-19 13:08 UTC
I'm working on a command line application which includes something like `ssh` wrapper. Basically what I'm doing is I'm resolving hostname myself, but then I want to pass all other parameters to the underlying `ssh` command. However, I've noticed that Click is consuming the first double dash (`--`) marker.

I was hoping Click has somewhere a variable containing all unprocessed arguments, but apparently, that's not the case, or at least I couldn't find it. So, in the end, I ended up adding one more click.Context option called `ignore_end_of_the_opts_marker` that tells Click to pass over the double dash, so if you combine it with `ignore_unknown_options`, you can pick all unprocessed arguments.

Eg.:

```python
@click.command(context_settings=dict(
    ignore_unknown_options=True,
    ignore_end_of_the_opts_marker=True
    ))
@click.argument('args', nargs=-1, type=click.UNPROCESSED)
@click.pass_context
def cli(ctx, args):
    print('All the arguments:', args)
```

I've noticed some people are also writing wrapper-like tools, so maybe more people would be interested in this option.

So far, I'm not sure if it's worth a Pull Request, let me know if it is, I've tried to document everything consistently with the rest of the code, but I can imagine there could be a better name for this option. Or maybe you have a better idea of how to solve this issue. 

Anyway, if someone is interested, here is my fork: https://github.com/Higgcz/click

**Comment by adzenith** [comment] 2020-12-16 16:22
Thoughts on making this into a PR? I would love to see this in upstream `click`.

**Comment by davidism** [comment] 2020-12-16 17:45
No need to ask to work on an issue. As long as the issue is not assigned to anyone and doesn't have have a linked open PR (both can be seen in the sidebar), anyone is welcome to work on any issue.

**Comment by Midnighter** [comment] 2021-06-24 16:38
I was looking for this possibility right now as it is becoming a common CLI pattern. Thank you for providing the code.

**Comment by sashati** [comment] 2021-09-23 16:48
Apparently, the Fork is kind of outdated. If anybody knows a way to resolve this issue?

**Comment by POD666** [comment] 2021-10-04 20:53
I end up with the following snippet (it obviously very limited to my use case but might be helpful):

```python
class HandleDoubleDashArg(click.Group):
    def parse_args(self, ctx, args):
        if "--" in args:
            # concat all options that follow double dash into tuple
            double_dash_idx = args.index("--")
            args = args[:double_dash_idx] + [tuple(args[double_dash_idx + 1 :])]
            # ['--arg', '123', '--', 'qwe', 'rty'] -> ['--arg', '123', ('qwe', 'rty')]
        else:
            # trick: feed an empty string as positional argument
            # so that the latests from args is considered as child command
            args.insert(-1, ())
            # ['--arg', '123', 'my_child_command'] -> ['--arg', '123', (), 'my_child_command']
        super(HandleDoubleDashArg, self).parse_args(ctx, args)


@click.group(cls=HandleDoubleDashArg, invoke_without_command=True)
@click.option("--arg")
@click.argument("double_dash_args")
@click.pass_context
def my_group_command(ctx, double_dash_args):
    # ...
    if ctx.invoked_subcommand is None:
        # ...
        pass


@my_group_command.command()
def my_child_command(ctx):
    # ...
    pass
```

**Comment by davidism** [comment] 2022-02-27 19:24
Pretty much a duplicate of #619. Just like if you need to pass an argument that looks like an option, use `--` if you need to pass a `--` as an argument.

```
wrapper -- ssh -c -- bash -v
```

**Closed by davidism** 2022-02-27 19:24 UTC
