### ISSUE TITLE
Facilitate custom formatting of console output

### ISSUE THREAD

**Issue by SamSchott** [pallets/click#1740] opened 2020-12-24 23:07 UTC
I can see from #590 that you are planning to restructure parts of click for the 9.0 release. Could I make a suggesting regarding clearer separation? Take this as a "wish list" issue.

It would be nice if the formatting of output would be clearly separated from the actual commands / command groups. This could enable users to easily implement custom formatters, for instance for help texts, error messages, prompts, etc. I am envisioning for instance abstract formatter base classes, similar to what already exists with the help formatter, extended to other parts of click. Those could be passed to constructors of commands or command groups to conveniently replace the default formatting.

According to the docs, some of the limited customisability is intentional. But maybe in this case it can be relaxed when enforcing strict requirements for such formatters?

**Comment by davidism** [comment] 2020-12-24 23:41
Duplicate of #561

This is generally not as straightforward as you've made it sound. Also, there are quite a few methods on the various core objects that control how things are formatted. Many of the things you describe already exist to one degree or another.

**Closed by davidism** 2020-12-24 23:41 UTC

**Comment by SamSchott** [comment] 2020-12-25 01:20
Thanks for the link, I somehow overlooked the existing issue.

As you say, a lot of custom formatting is already possible in some ways. An easier and more central way to implement custom formatting would still be great. I know it’s not straight forward, but it would be really nice!

**Comment by davidism** [comment] 2020-12-25 01:37
"More central" sounds nice, but it turns out they're basically in the place they need to be already. In the attempts I've made so far, moving things around never seems to make the formatting system any better.
