### ISSUE TITLE
Parse existing options even with --help flag

### ISSUE THREAD

**Issue by tall-josh** [pallets/click#1823] opened 2021-03-25 05:04 UTC
Hi I asked this on [SO](https://stackoverflow.com/questions/66668163/click-multi-command-pipeline-parse-availiable-parameters-when-help-is-called). For completeness, I figured I'd ask here.

---

I have a Click Multi Command Pipeline and I want to be able to display help messages depending on a required Option. But it seems when I add the -`-help` flag all the existing options are ignored. I have a workaround using `sys.argv` but as you could imagine, it can quickly become a bit of a mess. Here is an example:

```bash
$ python stack-exmple.py --help
Usage: stack-exmple.py [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...

Options:
  --help  Show this message and exit.

Commands:
  load-op

$ python stack-exmple.py load-op --help
Usage: stack-exmple.py load-op [OPTIONS]

Options:
  --op-type [A|B]  [required]
  --help           Show this message and exit.

$ python stack-exmple.py load-op --op-type A --help
Usage: stack-exmple.py load-op [OPTIONS]

Options:
  --op-type [A|B]  [required]
  --arg1 TEXT
  --help           Show this message and exit.

$ python stack-exmple.py load-op --op-type B --help
Usage: stack-exmple.py load-op [OPTIONS]

Options:
  --op-type [A|B]  [required]
  --arg1 TEXT
  --arg2 TEXT
  --help           Show this message and exit.

$ python stack-exmple.py load-op --op-type A --arg1 catA: cat
A: cat

$ python stack-exmple.py load-op --op-type B --arg1 cat --arg2 dog
B: cat, dog
```

The code the produces this output is:

```python
import click
from abc import ABC, abstractmethod
import sys

def display_dynamic_options(options):
    """
    Used as a decorator that will display click.options
    for a given list of options.

    """
    def decorator(f):
        for opt in reversed(options):
            opt(f)
        return f
    return decorator

class Foo:

    def __init__(self):
        self.clickop = None

    def do(self, **kwargs):
        if self.clickop is None:
            raise NotImplementedError()

        return self.clickop(**kwargs)

class ClickOp(ABC):

    @abstractmethod
    def __call__(self, **kwargs):
        pass

    @staticmethod
    @abstractmethod
    def get_options():
        pass

class FormatA(ClickOp):

    def __call__(
            self,
            *,
            arg1,
            **kwargs,
            ):
        print(f"A: {arg1}")

    @staticmethod
    def get_options():
        return [
                click.option("--arg1", type=str,),
        ]

class FormatB(ClickOp):

    def __call__(
            self,
            *,
            arg1,
            arg2,
            **kwargs,
            ):
        print(f"B: {arg1}, {arg2}")

    @staticmethod
    def get_options():
        return [
                click.option("--arg1", type=str,),
                click.option("--arg2", type=str,),
        ]

@click.group(
        "foo",
        chain=True,
        invoke_without_command=True,
)
def foo_group(
        ):
    pass

@foo_group.resultcallback()
def process_pipeline(
        processors,
        **kwargs,
        ):
    foo = Foo()
    for processor in processors:
        foo = processor(foo)

FORMATS = {"A": FormatA, "B": FormatB}

def get_options_when_load_op_is_called():
    if '--op-type' in sys.argv:
        op_type_idx = sys.argv.index("--op-type") + 1
        op_type_arg = sys.argv[op_type_idx]
        options = FORMATS[op_type_arg].get_options()
    else:
        options = []
    return options

@foo_group.command(
        'load-op',
        )
@click.option(
        "--op-type",
        type=click.Choice(["A", "B"]),
        required=True,
        )
@display_dynamic_options(get_options_when_load_op_is_called())
def load_op(**kwargs):

    def processor(foo):
        clickop = FORMATS[kwargs["op_type"]]()
        foo.clickop = clickop
        foo.do(**kwargs)
        return foo

    return processor


def cli():
    foo_group()

if __name__ == "__main__":
    cli()
```

Is there a way to obtain values for the partially provided cli arguments. Or is there a better _more Clickey_ way?

**Comment by davidism** [comment] 2021-03-25 05:20
Either this is a duplicate of #590, or, alternatively, using a custom help option that is not eager might work.

**Closed by davidism** 2021-03-25 05:20 UTC
