### ISSUE TITLE
open_file(..., 'x', atomic=True) error is misleading

### ISSUE THREAD

**Issue by gmacon** [pallets/click#1250] opened 2019-03-04 15:42 UTC
When using `open_file(path, 'x', atomic=True)`, the exception error message mentions the non-existent "overwrite" parameter. It looks like this message was copied from python-atomicwrites. Perhaps it should change to recommend that package instead?

* Click 7.0
* Python 3.7.2

**Comment by davidism** [comment] 2019-03-04 15:43
Is this issue asking for the message to be changed or to move to a different library?

**Comment by gmacon** [comment] 2019-03-04 15:44
I'm asking for the message to be changed to recommend that programmers who use that combination move to another library.

**Comment by davidism** [comment] 2019-03-04 15:45
Duplicate of #320

**Closed by davidism** 2019-03-04 15:45 UTC
