### ISSUE TITLE
click.secho() on Windows strips color information despite color=True.  (Windows only

### ISSUE THREAD

**Issue by zapta** [pallets/click#2791] opened 2024-10-24 01:51 UTC
### Summary:

``click.secho(,  color=True)`` is supposed to preserve text coloring despite writing to a pipe.  This works correctly on Mac (colors are preserved) but not on Windows the colors are stripped. 

### To reproduce:

Save the two files below in a directory and run ``python parent.py``.  The parent job will launch the child job which will output to the stdout pipe colored text. The parent jobs echoes that text and it should be colored (green).

File child.py
```
import click
import sys

# A message with color info.
msg = click.style("GREEN", fg="green")

# Dump message to stderr. This bypasses the parent job.
msg_hex = " ".join("{:02x}".format(ord(c)) for c in msg)
print(f"[CHILD ] Sending  (as hex): [{msg_hex}]", file=sys.stderr)

# Write to stdout. Should be send to the parent via pipe while
# preserving the coloring. 
# * reset=False prevents appending color off sequence.
# * nl="" prevents append EOL char.
click.secho(msg, color=True, reset=False, nl="")
```

File parent.py
```
import subprocess, time, os, sys

# Run the child process.
child = subprocess.Popen(["python", "child.py"],
                     stdout=subprocess.PIPE,
                     stderr=None)

# Dump the captured stdout.
for line in iter(child.stdout.readline, b''):
    # Dump line as hex.
    hex_dump =  " ".join("{:02x}".format(c) for c in line)
    print(f"[PARENT] recieved (as hex): [{hex_dump}]")

    # Dump line as text. Should print colored text.
    str = line.decode("utf-8")
    print(f"[PARENT] recieved (as str): {str}")
```

### Expected abehavior:

On Mac the behavior is correct and the text that the parent echoes from the pipe is colored.

<img width="533" alt="image" src="https://github.com/user-attachments/assets/7d8dff6f-0c2d-4e91-9863-cb274eace96e">

### Actual behavior:

On windows, however, the ansi colors are stripped (see the shorter hex string) and the output text is not colored.

![image](https://github.com/user-attachments/assets/f994d8ac-1fa1-472b-a770-07ca038fc5f2)

### Environment:

- Python version:  3.12.0
- Click version:  8.1.7

**Comment by davidism** [comment] 2024-10-24 04:25
Duplicate of #2606

**Closed by davidism** 2024-10-24 04:25 UTC
