### ISSUE TITLE
Exception in _tempfilepager on Windows

### ISSUE THREAD

**Issue by j-bennet** [pallets/click#1956] opened 2021-06-11 16:47 UTC
When using `click.echo_via_pager`, an exception is thrown in `_tempfilepager` on Windows when trying to delete the file.

Original issue in pgcli: https://github.com/dbcli/pgcli/issues/1270.

I don't have access to a Windows machine to create a minimal reproducible example, sorry. Here is the traceback from the original reporter:

```
Traceback (most recent call last):
  File "C:\Python\3.8\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\3.8\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<redacted>\venv\Scripts\pgcli.exe\__main__.py", line 7, in <module>
  File "<redacted>\venv\lib\site-packages\click\core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "<redacted>\venv\lib\site-packages\click\core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "<redacted>\venv\lib\site-packages\click\core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<redacted>\venv\lib\site-packages\click\core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "<redacted>\venv\lib\site-packages\pgcli\main.py", line 1336, in cli
    pgcli.run_cli()
  File "<redacted>\venv\lib\site-packages\pgcli\main.py", line 765, in run_cli
    query = self.execute_command(text)
  File "<redacted>\venv\lib\site-packages\pgcli\main.py", line 684, in execute_command
    self.echo_via_pager("\n".join(output))
  File "<redacted>\venv\lib\site-packages\pgcli\main.py", line 1085, in echo_via_pager
    click.echo_via_pager(text, color=color)
  File "<redacted>\venv\lib\site-packages\click\termui.py", line 302, in echo_via_pager
    return pager(itertools.chain(text_generator, "\n"), color)
  File "<redacted>\venv\lib\site-packages\click\_termui_impl.py", line 357, in pager
    return _tempfilepager(generator, "more <", color)
  File "<redacted>\venv\lib\site-packages\click\_termui_impl.py", line 440, in _tempfilepager
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '%TEMP%\\tmp_cpxsj61'
```

Environment:

- Python version: 3.8.0
- Click version: 8.0.0
- Windows 10 version 21H1

**Comment by davidism** [comment] 2021-06-11 17:44
Duplicate of #1905

**Closed by davidism** 2021-06-11 17:44 UTC
