### ISSUE TITLE
click.Path(resolve=True) breaks with relative symlinks

### ISSUE THREAD

**Issue by ulope** [pallets/click#1958] opened 2021-06-14 14:29 UTC
In #1825 a fix for path options containing symlinks was added.
Unfortunately this breaks with paths containing relative symlinks.

The problem is that those lines https://github.com/pallets/click/blob/8b48450d5d63c747600e069d4c3e2274f41c8360/src/click/types.py#L841-L843 

interact in a way that makes a relative symlink get resolved against the current directory, not the one containing the symlink.

Reproducing example:

`main.py`:
```python
from os import getcwd
from os.path import abspath, realpath

import click


@click.command()
@click.option("--path-resolved", type=click.Path(dir_okay=True, file_okay=False, resolve_path=True))
@click.option("--path", type=click.Path(dir_okay=True, file_okay=False, resolve_path=False))
def main(path_resolved, path):
    cwd = getcwd()

    path_rel = abspath(path).replace(cwd, ".")
    path_resolved_rel = abspath(path_resolved).replace(cwd, ".")
    path_resolved_manual_rel = realpath(path).replace(cwd, ".")

    print("path                      ", path_rel)
    print("path (resolved 'manually')", path_resolved_manual_rel)
    print("path_resolved             ", path_resolved_rel)
    print()

    assert path_resolved_manual_rel == path_resolved_rel


if __name__ == '__main__':
    main()
```

```shell
$ tree
.
├── main.py
└── root
    ├── a -> b
    └── b

3 directories, 1 file

$ python main.py --path-resolved root/a --path root/a
path                       ./root/a
path (resolved 'manually') ./root/b
path_resolved              ./b

Traceback (most recent call last):
[... snip ...]
AssertionError
```

Environment:

- Python version: 3.9.2
- Click version: 8.0.1

**Comment by davidism** [comment] 2021-06-14 14:49
Duplicate of #1921

**Closed by davidism** 2021-06-14 14:49 UTC
