### ISSUE TITLE
Visually group options in the help printout

### ISSUE THREAD

**Issue by b52** [pallets/click#604] opened 2016-07-08 08:30 UTC
I would like to group certain options in sections in the help printout, to make it more user-friendly. This is very useful if you happen to have a lot of options for different parts of your software. Since I didn't find any docs on how to accomplish that, I assume it's not yet implemented, but feel free to correct me.

**Comment by pombredanne** [comment] 2017-07-11 16:22
I might need something like this too. My initial approach would be a Command subclass on the one hand that handles the `format_options()` differently and an alternative `option` decorator that would accept an extra `option_group` arg and attach it as an attribute to the Option instance.  `option_group` would then be used in `format_options()` to group the option in the formatted help.

**Comment by alalazo** [comment] 2018-01-19 16:29
Was looking for something like this and couldn't find it in the docs. Is there any known solution to this problem?

**Comment by pombredanne** [comment] 2018-01-20 23:32
@alalazo I am using a custom [Command class](https://github.com/nexB/scancode-toolkit/blob/a1c7053871d4de986baba6d2c34b24016d2fcb66/src/scancode/cli.py#L249) and a custom [Option class](https://github.com/nexB/scancode-toolkit/blob/a1c7053871d4de986baba6d2c34b24016d2fcb66/src/scancode/__init__.py#L116) with a help_group extra arg for this.

There are a few extra things too such as setting an options sort_order (my options can be contributed by external plugins) and telling which option an option depends on: either requires and conflicts with other options names, such as mutually exclusive options and co-dependencies.

**Comment by fdavis** [comment] 2018-05-15 20:30
Closing as duplicate of https://github.com/pallets/click/issues/513

**Closed by fdavis** 2018-05-15 20:30 UTC
Labels: duplicate, enhancement
