### ISSUE TITLE
Command names with underscores must be invoked with dashes instead when upgrading from 6.7 to 7.0

### ISSUE THREAD

**Issue by CrescentFresh** [pallets/click#1123] opened 2018-09-26 14:07 UTC
Click 7.0 is breaking upstream packages, in our case `mschematool` (issue reported there: https://github.com/aartur/mschematool/issues/11).

After upgrading from 6.7 to 7.0, the `init_db` command can no longer be found.

```
$ mschematool xyz init_db
Usage: mschematool [OPTIONS] DBNICK COMMAND [ARGS]...
Try "mschematool --help" for help.

Error: No such command "init_db".
ERROR: Job failed: exit code 2
```

**Comment by ThiefMaster** [comment] 2018-09-26 14:10
You should not allow your CI to silently install a newer major version.

(FWIW, this could be a problem with click, but it's hard to say without seeing a minimal code example that works in click 6 and breaks in click 7)

**Comment by CrescentFresh** [comment] 2018-09-26 14:14
Hey man, we just install mschematool. Its dependencies are its dependencies.

Hopefully the author of that lib will chime in on the other issue.

**Comment by davidism** [comment] 2018-09-26 14:15
I can't reproduce this issue. Upgrading a sample project from 6.7 to 7.0 does not cause some commands not to be found. Please include a minimal reproducible example when reporting issues.

**Comment by adityanatraj** [comment] 2018-09-26 21:03
we ran into this issue and noticed that commands that contained underscores are now expected with dashes. i'm trying to find out when this changed myself.

**Comment by ThiefMaster** [comment] 2018-09-26 21:04
As ugly as underscores in commands are, maybe it'd be better to normalize them to dashes and accept both?

**Comment by CrescentFresh** [comment] 2018-09-26 21:51
So if I understand this correctly:

a) commit https://github.com/pallets/click/commit/5d1df0e042b2f8b0dee8f6dd9ce74edce331a950 intentionally broke bc with commands with underscores in them, instead requiring dashes
2) python methods to my knowledge cannot have dashes in them, yet these methods are still the thing command authors are expected to decorate with click

The combination of which go boom.

So are command authors still recommended to use underscores in their method names or not?

**Comment by ThiefMaster** [comment] 2018-09-26 21:54
That's the whole point of the change: Have dashes in the commands while having valid python code (underscores)

**Comment by CrescentFresh** [comment] 2018-09-26 22:12
How is a user of a tool that uses click under the hood supposed to know this? As you point out command authors don't have to do anything differently, yet the users of said tooling - who don't even know that click is being used under the hood - have to know to not use underscores in command line parameters.

**Comment by mitsuhiko** [comment] 2018-09-26 22:13
So the core of the issue here is that people don't pin dependencies. Click 7 is not compatible with Click 6 the same way it was not compatible with Click 5. I think this time around it's just more noticable.

**Comment by ThiefMaster** [comment] 2018-09-26 22:13
Like @davidism  mentioned, this was poorly communicated in the changelog. Regardless of this, tool developers should not allow any future major version change when specifying their requirements, to avoid such surprises.

**Comment by mitsuhiko** [comment] 2018-09-26 22:14
One workaround I see is that we could also look for commands with dashes when someone tries a command with underscores.

**Comment by ThiefMaster** [comment] 2018-09-26 22:15
What about doing that in both directions? (and throw an exception if someone registers two different versions that only differ in dash/underscore usage)

**Comment by adityanatraj** [comment] 2018-09-26 22:16
@davidism thanks for the commit ref and the explanation. I think it could have been more prominently described in the changelog (given python naming conventions would imply an insignificant number of people would hit this) but I do understand it was a major release. On our side, probably we should have pinned our dependencies better -_-. 

perhaps it makes sense to attempt both for some interim period? of course, you'd have to dedupe when someone goes wild and attempts to register both styles...

@di nice to see you!

**Comment by PorkShoulderHolder** [comment] 2018-09-27 16:42
It would have made sense to accept both formats and issue a `DeprecationWarning` when underscored commands were called, and then phase out underscores in a later version, issuing an error that describes the reason precisely (i.e. "now you gotta put dashes in version 7.0"). This change broke a bunch of commands for me...

**Comment by davidism** [comment] 2018-09-27 16:59
You can still use underscores by specifying the command names explicitly. It's just that the default is now to replace dashses, whereas before you would have had to specify *those* explicitly.

So if you want to upgrade your app to 7.0 but continue using the old names, you can name them explicitly, or use a `Command` subclass that doesn't have the new behavior. There are upgrade strategies here, it just means Click 7.0 is not a drop-in upgrade in some cases.

**Comment by CrescentFresh** [comment] 2018-09-27 18:37
Stop changing the title, yours is unclear and has typos.

**Comment by davidism** [comment] 2020-02-22 19:23
At this point, it's been so long since 7.0 that I think the issue is well understood and handled in projects. Ideally, we would have addressed this sooner, but things got away from me and no one followed up with it.

Projects have had a few options. First, as pointed out earlier, you should always pin your dependencies in order to control how your projects is installed and when you upgrade. You can specify command names manually, like `@click.command("name_with_underscores")`, or update documentation to use the names with dashes. Or there's a nice third option, that unfortunately I didn't figure out until recently. I wish I had been able to post it sooner.

During recent discussion in chat, we were considering adding a `match_underscore_names` context setting that would replaces dashes with underscores if the name wasn't found. When I went to implement it, I noticed that this behavior already exists in a more general fashion. If a command is not found and the context has a `normalize_token_func` set, that will be called to potentially get a new name to look up.

```python
import click

def normalize(name):
    return name.replace("_", "-")

@click.group(context_settings={"normalize_token_func": normalize})
def group():
    pass

@group.command()
def show_greeting():
    click.echo("Hello, World!")

if __name__ == "__main__":
    group()
```

```
$ python example.py show_greeting
Hello, World!
```

I will ensure this is prominent in the docs, possibly as part of #1221. At this point, I don't think it's necessary to add any code to Click, so I'm going to close this.

**Closed by davidism** 2020-02-22 19:23 UTC
