### ISSUE TITLE
Group args not displayed in subcommand help

### ISSUE THREAD

**Issue by jmorel** [pallets/click#1710] opened 2020-11-10 12:39 UTC
The help text of a subcommand doesn't mention the parent group's args, which makes the "Usage" section misleading. 

Using the following script:

```python
import click

@click.group()
@click.argument('group_arg')
def app(group_arg):
    pass

@app.command()
def subcommand():
    pass

if __name__ == '__main__':
    app()
```

### Expected Behavior

The group's arguments are included in the usage section.

```
$ python cli.py foo subcommand --help
Usage: cli.py GROUP_ARG subcommand [OPTIONS]

Options:
  --help  Show this message and exit.
```

### Actual Behavior

The group's arguments are not included.

```
$ python cli.py foo subcommand --help
Usage: cli.py subcommand [OPTIONS]

Options:
  --help  Show this message and exit.
```

This is not an issue when working with the CLI directly since you have to provide all args to be able to display the help text. 

However it is one when you are extracting the result of --help for documentation purposes (or in my case using [sphinx-click](https://github.com/click-contrib/sphinx-click)): readers won't be able to copy/paste/edit commands from the docs and the results they would get by doing so would be very confusing.

### Environment

* Python version: 3.7.7
* Click version: 7.1.2

**Comment by davidism** [comment] 2020-11-10 13:48
Duplicate of #1475

**Closed by davidism** 2020-11-10 13:48 UTC

**Comment by jmorel** [comment] 2020-11-10 14:20
My bad, I did a search in open issues, it didn't occur to me that the issue could already have been reported and fixed.
