### ISSUE TITLE
Type conversion no longer applied to defaults when invoking a default subcommand in 8.0.2

### ISSUE THREAD

**Issue by jwodder** [pallets/click#2090] opened 2021-10-09 19:52 UTC
Consider the following code:

```python
import click

@click.group(invoke_without_command=True)
@click.pass_context
def main(ctx):
    if ctx.invoked_subcommand is None:
        ctx.invoke(ctx.command.commands["foo"])

@main.command()
@click.option("--bar", type=int, default="42")
def foo(bar):
    click.echo(repr(bar))

if __name__ == "__main__":
    main()
```

Prior to Click 8.0.2, this worked correctly; invoking the script with just `python3 scriptname.py` output `42`.  However, with the release of v8.0.2, the `type=int` is no longer applied to `--bar`'s default when invoking the command without a subcommand; in that case, the output is `'42'` (a string).

(Yes, I know that, in this specific case, it would be better to set `default=42`, but in my actual use-case, the `default` is a callable that does I/O, and I'd like to avoid evaluating it unless it's needed.)

Environment:

- Python version: 3.9.7
- Click version: 8.0.2

**Comment by davidism** [comment] 2021-10-09 23:40
Duplicate of #2089

**Closed by davidism** 2021-10-09 23:40 UTC
