### ISSUE TITLE
`runner.invoke` with inputs raising. ValueError('Something went wrong, Stdin is not a terminal.') 

### ISSUE THREAD

**Issue by lalmei** [pallets/click#2309] opened 2022-06-09 14:50 UTC
I use the `click`  Runner to test my click application. It calls a third party, copier, python package that starts a series of prompts in terminal
The application runs with no problem in the terminal. However, during testing at the prompt stage, I get the following error:

`ValueError('Something went wrong, Stdin is not a terminal.') `.

inputs are passed a string with the appropriate number of `\n`

Working on a minimal example. 

Environment:

- Python version: v3.9.12
- Click version: v8.1.3

**Comment by davidism** [comment] 2022-06-09 14:55
This sounds like an issue with copier, or a duplicate of https://github.com/pallets/click/issues/843.

**Closed by davidism** 2022-06-09 14:55 UTC

**Comment by lalmei** [comment] 2022-06-09 14:58
I understand, but is there a way to emulate the inputs further? I tried mocking isatty() in sys.stdin was unsuccessful

**Comment by davidism** [comment] 2022-06-09 14:59
You're not required to use the test runner. If you have other requirements that need to be satisfied when testing, you can write whatever Python code is necessary to perform the test.

**Comment by lalmei** [comment] 2022-06-09 15:04
I understand; I love like how clean the runner setup is. I was hoping there were other types I could use for input arguments or IO wrappers that might emulate the tty better?
