### ISSUE TITLE
Passing an instance of Pathlib.Path to CliRunner.invoke() gets a TypeError

### ISSUE THREAD

**Issue by alexwlchan** [pallets/click#1324] opened 2019-05-27 07:53 UTC
Consider the following example:

```python
from pathlib import Path

import click
from click.testing import CliRunner


@click.command()
@click.argument("DIRNAME")
def print_directory(dirname):
    print(dirname)


runner = CliRunner()
print(runner.invoke(print_directory, ["example"]))
print(runner.invoke(print_directory, [Path("example")]))
```

With Python 3.6.4 and click 7.0, this is the output you get:

```
<Result okay>
<Result TypeError("object of type 'PosixPath' has no len()",)>
```

This can be easily fixed by wrapping in `str()`, i.e.,

```python
print(runner.invoke(print_directory, [str(Path("example"))]))
```

But in general I've got used to the implicit contract (at least in the standard library) that I can use a `Path` object anywhere I can use a string representation of a path. Since paths are often the arguments to command-line tools, it'd be nice to be able to use a Path object here as well.

Alternatively, raise a more helpful TypeError if you pass a non-string object into `invoke()` – I spent a while poking around in my code to see where I was calling `len()` on the wrong object before realising it was actually coming from click.

**Comment by joshuastorck** [comment] 2019-05-31 14:37
This code change would solve your problem in core.BaseCommand.main:

```python
        if args is None:
            args = get_os_args()
        else:
            args = [arg.__fspath__() if hasattr(arg, "__fspath__") else arg
                    for arg in args]
```
However, that would still not make support for other types work, such as integers. In general, the parser assumes all inputs are strings. To properly handle this, a pre-processing step would have to be done to determine which arguments on the command line are associated with which types. However, this adds a lot of complexity, since command line arguments like dashes need to be handled. This would be a huge overhaul to the parser and is probably not a good idea.

I suggest closing this issue and just using the noted workaround.

**Closed** 2019-05-31 14:37 UTC
Labels: good first issue, save-for-sprint

**Comment by alexwlchan** [comment] 2019-05-31 15:31
I think it’s reasonable to say “we can’t coerce all arguments to strings”, but the confusing error message remains.

Would it be possible to add a check something like:

```
if not all(isinstance(arg, string_types) for arg in args):
    raise TypeError(“args must all be strings; got %r”)
```

to make it more obvious when somebody has made this mistake?

**Comment by davidism** [comment] 2019-05-31 21:16
If the documentation is unclear that the `invoke`-related APIs expect strings, that's something I'm ok with changing, but otherwise I think this is just expected behavior. In general, and I know this is somewhat contradictory given that Click does a bunch of validation, Python shouldn't be checking the types of arguments.
