### ISSUE TITLE
Styled output support for JupyterLab

### ISSUE THREAD

**Issue by munael** [pallets/click#1271] opened 2019-04-01 15:24 UTC
Not sure if this's a goal. But some issues mention support for Jupyter Notebook, and I'm not sure why it doesn't work in Jupyter Lab. It prints fine, but with no styling.

* Python 3.7.1
* Click 7.0
* Jupyter Lab 0.35.4

**Comment by davidism** [comment] 2019-04-01 15:37
duplicate of #1186

**Comment by RonnyPfannschmidt** [comment] 2020-05-20 05:23
based on the comment in #1186 this one has to reopen as its a different kernel with a different io stream

**Comment by awalvie** [comment] 2020-10-21 03:05
I have successfully duplicated the issue on JupyterLab in Windows:
Input:

```python
import click

print(click.style('Hello World!', fg='green', bold=True, underline=True))
click.echo(click.style('Hello World!', fg='green', bold=True, underline=True))
click.echo(click.style('ATTENTION!', blink=True))
click.echo(click.style('Some things', reverse=True, fg='cyan'))
```
Output:

![image](https://user-images.githubusercontent.com/35740094/96667930-a712df80-1377-11eb-8047-fd678f2f627d.png)

So we don't have any styling whatsoever here, which is expected. 
Interestingly enough I found another inconsistency that's not just limited to JupyterLab, passing the same input into a test file gives us the following result.

![image](https://user-images.githubusercontent.com/35740094/96668043-e9d4b780-1377-11eb-8a3e-a278c25b0f88.png)

Using `print` leads to the expected style, with bold and underline, whereas using `click.echo` does not enable them.
This was pointed out in the following comment -> https://github.com/pallets/click/pull/1186#issuecomment-478637599

**Comment by davidism** [comment] 2020-10-21 13:12
You'll have to be more specific about how you're writing to a file for me to say, but at least the `print` behavior is expected. `click.echo` checks the stream to see if it should strip the color codes, `print` does not. That's the whole issue, there's a special check to tell it that Jupyter kernel streams are ok, but it still doesn't detect JupyterLab streams.

**Comment by awalvie** [comment] 2020-10-21 13:30
Roger that! I'll get right on it, thanks for the clarification.

**Closed** 2021-02-25 00:38 UTC
Labels: good first issue
