### ISSUE TITLE
interaction issue with "python -m pdb" (click 6, windows, python 2.7)

### ISSUE THREAD

**Issue by zogzog** [pallets/click#655] opened 2016-09-16 10:26 UTC
The following module : 

```
import click

#@click.command()
def foo():
    hi

foo()
```

will drop into the python debugger around 'hi' (the NameError) if invoked with
python -m pdb ./hi.py

but if we activate the click decorator, it will enter a loop like:

```
PS C:\src> python -m pdb  .\hi.py
> c:\src\hi.py(1)<module>()
-> import click
(Pdb) c
Usage: hi.py [OPTIONS]

Error: Got unexpected extra argument (.\hi.py)
The program exited via sys.exit(). Exit status:  2
> c:\src\hi.py(1)<module>()
-> import click
(Pdb) c
Usage: hi.py [OPTIONS]
```

Definitely not reproduced on a linux machine (python 2.7).
Is it a purely local issue ? Something windows related ?

Thanks in advance.

**Comment by untitaker** [comment] 2016-09-18 07:27
I can't reproduce it on my LInux either. Would be nice if somebody would spin up Windows and test this, but I suspect it's not an issue on your side.

At first sight this actually seems like a PDB issue (partially at least) since all the arguments are completely mixed up and Click is getting `./hi.py` passed as arg.

**Comment by whistler** [comment] 2017-10-26 22:06
I get the same issue on OSX Python 3.6.2

**Comment by segevfiner** [comment] 2018-10-07 16:55
Might be a duplicate of https://github.com/pallets/click/issues/536. This one is older, but https://github.com/pallets/click/issues/536, has more activity.

Not sure what could possibly cause this on OS X... we simply use `sys.argv` there...

**Comment by int19h** [comment] 2019-07-11 19:44
It does repro on Win32, and that is indeed because of #536. You can observe that it has the same workaround, i.e. instead of:
```py
foo()
```
you must do
```py
foo(sys.argv[1:])
```
So that Click doesn't try to circumvent `sys.argv`.

**Comment by jcrotts** [comment] 2021-02-27 19:47
I'm not seeing this on Windows running Python 3. Closing since it seems to be a Python 2 only issue, and we are no longer supporting Python 2. If someone can replicate this on Python 3, please post the failing test case, and I'll reopen the issue.

**Closed by jcrotts** 2021-02-27 19:47 UTC
