### ISSUE TITLE
pyright support

### ISSUE THREAD

**Issue by mehdigmira** [pallets/click#2566] opened 2023-07-16 19:22 UTC
```python
@click.group()
def cli():
  pass
```

with the code snippet above, pyright reports `Untyped function decorator obscures type of function; ignoring decorator`

The error is caused by the following overload

```python
# variant: name omitted, cls _must_ be a keyword argument, @group(cmd=GroupCls, ...)
# The _correct_ way to spell this overload is to use keyword-only argument syntax:
# def group(*, cls: t.Type[GrpType], **attrs: t.Any) -> ...
# However, mypy thinks this doesn't fit the overloaded function. Pyright does
# accept that spelling, and the following work-around makes pyright issue a
# warning that GrpType could be left unsolved, but mypy sees it as fine. *shrug*
@t.overload
def group(
    name: None = None,
    cls: t.Type[GrpType] = ...,
    **attrs: t.Any,
) -> t.Callable[[_AnyCallable], GrpType]:
    ...
```

The comment suggests the author is aware of the issue ? Is there some way this could be fixed ?
This makes 8.1.5 version nearly unusable for codebases relying on pyright as a typechecker

Environment:

- Python version: 3.11
- Click version: 8.1.5

**Comment by davidism** [comment] 2023-07-16 19:50
Duplicate of #2565

**Closed by davidism** 2023-07-16 19:50 UTC
