### ISSUE TITLE
prompt + hide_input shows a GetPassWarning if no tty

### ISSUE THREAD

**Issue by eddawley** [pallets/click#906] opened 2017-12-22 22:06 UTC
getpass requires a tty so it can ensure output won't be echoed.  If it doesn't have one, it will warn.  The [docs](https://pymotw.com/2/getpass/) suggest checking for a tty before use so it would be nice if prompt() did that for us.

Simple example:
```
import click, sys

print sys.stdin.isatty()
click.prompt('test', hide_input=True)
```

Execution:
```
[vagrant@test ~]$ python a.py 
True
test: 
[vagrant@test ~]$ ssh localhost python a.py
False
test: /usr/lib64/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
asdf

[vagrant@test ~]$
```

**Comment by davidism** [comment] 2020-07-02 12:56
I'm not clear why the fact that `getpass` warns users if their input might not be secure is an issue. The link you've provided are not the docs, they're a person's blog about the docs. The actual docs don't say to use that workaround, they just document the cases that will cause the warning.

Since the issue is old and there's not a justification for the change, I'm going to close this for now.

**Closed by davidism** 2020-07-02 12:56 UTC
Labels: bug, good first issue
