### ISSUE TITLE
group options that are required shouldn't be required for calling --help

### ISSUE THREAD

**Issue by gergelyk** [pallets/click#2465] opened 2023-03-06 10:24 UTC
Consider CLI with two commands in the same group. Both commands require the same option, so it seams reasonable to have this option set at the group level and configure it as *required*. E.g.:

```sh
python3 app.py --name World say-hello
python3 app.py --name World say-bye
```

```python
import click
from types import SimpleNamespace

@click.group
@click.pass_context
@click.option('--name', required=True)
def main(ctx, name):
    ctx.obj = SimpleNamespace(name=name)

@main.command()
@click.pass_obj
def say_hello(ctx_obj):
    print(f'Hello {ctx_obj.name}!')

@main.command()
@click.pass_obj
def say_bye(ctx_obj):
    print(f'Bye {ctx_obj.name}!')

if __name__ == '__main__':
    main()
```

Now the drawback is that  `python3 app.py say-bye --help` raises an error, because `--name` is missing. I suspect this as not intended.

Python version: 3.9.6
Click version: 8.1.3

**Comment by davidism** [comment] 2023-03-06 14:29
Duplicate of #295, #814, etc.

**Closed by davidism** 2023-03-06 14:29 UTC
