### ISSUE TITLE
completion for bash do not work for not english locale

### ISSUE THREAD

**Issue by pat1** [pallets/click#2177] opened 2022-01-19 19:58 UTC
everything at
https://github.com/platformio/platformio-core/issues/4154

**Comment by davidism** [comment] 2022-01-19 20:00
This is not how to report an issue. Be sure to follow the issue template you deletedd when posting this. Include all the details necessary to describe and reproduce the issue directly in the report.

**Comment by davidism** [comment] 2022-01-19 20:01
Duplicate of #1940

**Closed by davidism** 2022-01-19 20:01 UTC
