### ISSUE TITLE
Test runner does not flush `sys.stderr` before assembling `Result`

### ISSUE THREAD

**Issue by jdevera** [pallets/click#1808] opened 2021-03-05 17:48 UTC
`CliRunner` from `click.testing` flushes `sys.stdout` before obtaining its contents to assemble a `Result` object, but does not do so for `sys.stderr` when the `mix_stderr` parameter is set to `False`.

```python
import sys
import click
from click.testing import CliRunner

@click.command()
def hello():
    print("Check", file=sys.stderr)

def test_hello_world():
    runner = CliRunner(mix_stderr=False)
    result = runner.invoke(hello)
    assert result.exit_code == 0
    assert result.stderr == 'Check\n'
```

I would expect that test to pass, but instead, `result.stderr` is empty:

```
>       assert result.stderr == 'Check\n'
E       AssertionError: assert '' == 'Check\n'
E         - Check

test_click.py:13: AssertionError
```

Environment:

- Python version: 3.7.5
- Click version: 7.1.2

**Comment by davidism** [comment] 2021-03-05 17:51
Duplicate of #1761. Not a bug in Click but a misunderstanding of how `print` works with `sys.stderr`. This is why `click.echo` exists.

**Closed by davidism** 2021-03-05 17:51 UTC

**Comment by jdevera** [comment] 2021-03-05 19:42
Thank you, hadn't seen that one.

However, for what it's worth, I share the same view the OP posted in the last comment in #1761.

There are lots of prints to stderr in the guts of what I am calling with `click`, and replacing it with `click.echo` would not be an option for me.

In normal program execution, when I run this on the shell, stderr gets flushed at the end with no extra explicit flushes. The test runner flushes stdout and flushing stderr would yield the results that one would expect from running a command.

Even when this is a python thing, a solution in the test runner would make it work. Would you reconsider? I'm happy to make a PR for this.
