### ISSUE TITLE
Feature request: localization support

### ISSUE THREAD

**Issue by joernheissler** [pallets/click#1542] opened 2020-04-27 11:29 UTC
Hello!

Are there any plans to add localization support?

I.e. all help/usage texts that a click application displays to the user should be in the user's preferred language.

As click heavily relies on docstrings, this won't work:

```python3
@click.command
def foo():
    _("""localized help text""")
    pass
```

Cheers

**Comment by davidism** [comment] 2020-04-27 13:46
Duplicate of #303

**Closed by davidism** 2020-04-27 13:46 UTC
