### ISSUE TITLE
command collection with multiple different options on the groups?

### ISSUE THREAD

**Issue by silky** [pallets/click#1032] opened 2018-06-04 00:15 UTC
consider the following example:

```
#!/usr/bin/env python

import click

@click.group()
@click.option("--c1", type=str, required=True)
def cli1(c1):
    pass

@cli1.command()
def cmd1():
    """Command on cli1"""
    print("cmd1")

@click.group()
@click.option("--c2", type=str, required=True)
def cli2(c2):
    pass

@cli2.command()
def cmd2():
    """Command on cli2"""
    print("cmd2")

cli = click.CommandCollection(sources=[cli1, cli2])

if __name__ == '__main__':
    cli()
```

the options get lost. there is no way to pass values to them.

how can i make this example work?

**Comment by davidism** [comment] 2018-06-06 13:06
Duplicate of #347 

See #341 for a workaround after creating the collection. I know a command's options are introspectable somehow, so you could manually pull the options off and put them back on the new collection as a workaround until the duplicate is addressed.

**Closed by davidism** 2018-06-06 13:06 UTC
