### ISSUE TITLE
Silent failure with option/command starting with "/"

### ISSUE THREAD

**Issue by watsonjj** [pallets/click#2316] opened 2022-07-05 08:39 UTC
When an incorrect sub-command or argument which begins with "/" is used, no error is raised. Instead the help message is shown and the command ends with exit code 0.

For example:
```
(sstcam) ~/Software/sstcam-eventbuilder  develop*    $ sstcam-eventbuilder test                                                                                                                              5.4G 1.76 10:28
Usage: sstcam-eventbuilder [OPTIONS] COMMAND [ARGS]...
Try 'sstcam-eventbuilder --help' for help.

Error: No such command 'test'.
```
```
(sstcam) ~/Software/sstcam-eventbuilder  develop*    $ sstcam-eventbuilder -test                                                                                                                             5.4G 1.77 10:28
Usage: sstcam-eventbuilder [OPTIONS] COMMAND [ARGS]...
Try 'sstcam-eventbuilder --help' for help.

Error: No such option: -t
```
```
(sstcam) ~/Software/sstcam-eventbuilder  develop*    $ sstcam-eventbuilder --test                                                                                                                            5.4G 1.75 10:28
Usage: sstcam-eventbuilder [OPTIONS] COMMAND [ARGS]...
Try 'sstcam-eventbuilder --help' for help.

Error: No such option: --test
```
```
(sstcam) ~/Software/sstcam-eventbuilder  develop*    $ sstcam-eventbuilder /test                                                                                                                            5.37G 1.72 10:28
Usage: sstcam-eventbuilder [OPTIONS] COMMAND [ARGS]...

  Event builder for the SST camera.

Options:
  --port INTEGER  Port on which the gRPC server is hosted.  [default: 50051]
  --ip TEXT       IP address of the gRPC server.  [default: localhost]
  --help          Show this message and exit.

Commands:
  calibration  Commands relating to the online calibration.
  display      Commands relating to the real-time event display.
  gate         Commands relating to the queued events at the gate.
  listener     Commands relating to the UDP packet listener.
  mock         Commands relating to the mock camera UDP server.
  pipeline     Commands relating to the event builder pipeline.
  server       Commands relating to the gRPC server.
```

I would expect the last command to also error.
I believe the issue #1929 and PR #1930 are related to this bug.

Environment:

- Python version: 3.8.0
- Click version: 8.1.3

**Comment by davidism** [comment] 2022-07-05 12:28
Duplicate of https://github.com/pallets/click/issues/1322

**Closed by davidism** 2022-07-05 12:28 UTC
