### ISSUE TITLE
Support Generics for click.Context to Enhance Type Safety

### ISSUE THREAD

**Issue by remohammadi** [pallets/click#2794] opened 2024-10-29 21:37 UTC
Currently, the `ctx.obj` attribute in `click.Context` is dynamically typed. This can lead to type-related errors at runtime, especially in larger CLI applications with complex object structures.

To improve type safety and developer experience, I propose adding support for generics to the `Context` class. This would allow developers to specify the type of `ctx.obj` when defining commands, enabling static type checking and better IDE support.

**Example:**

```python
from typing import Generic, TypeVar

T = TypeVar('T')

class Context(click.Context, Generic[T]): 
    obj: T  # Type of ctx.obj is now determined by the generic type argument

@click.command()
@click.pass_context
def my_command(ctx: Context[BlahBlah]):
    # ctx.obj is now correctly inferred as type BlahBlah
    print(ctx.obj.some_attribute) 
```

**Benefits:**

- **Improved Type Safety:** Catches type errors during development, reducing runtime surprises.
- **Enhanced Code Readability:**  Clearly defines the expected type of `ctx.obj` for each command.
- **Better IDE Support:** Enables autocompletion and type hints, improving developer productivity.
- **Increased Maintainability:**  Makes it easier to refactor and understand code, especially in complex projects.

**Comment by davidism** [comment] 2024-10-29 22:17
Duplicate of #2493

**Closed by davidism** 2024-10-29 22:17 UTC
