### ISSUE TITLE
Option to force ANSI color codes or disable TTY detection

### ISSUE THREAD

**Issue by gdewald** [pallets/click#2282] opened 2022-05-09 19:51 UTC
[ANSI Colors](https://click.palletsprojects.com/en/8.1.x/utils/#ansi-colors) are automatically disabled in some cases, I would like to request some option to disable this feature for cases where the output may be captured outside of a TTY but color codes are still desired.

Specific use case: GitLab CI [supports color codes in output](https://docs.gitlab.com/ee/ci/yaml/script.html#add-color-codes-to-script-output), however Click applications don't appear to output color codes when executed in this context.

**Comment by davidism** [comment] 2022-05-09 20:04
Essentially duplicate of https://github.com/pallets/click/issues/2207, but with the bool flipped.

**Closed by davidism** 2022-05-09 20:04 UTC
