### ISSUE TITLE
Handling of argv on windows platform

### ISSUE THREAD

**Issue by mjos** [pallets/click#536] opened 2016-03-14 15:53 UTC
Hi we have encountered the following problem. We were trying to profile click-enabled application on windows platform in PyCharm. Profiling the is done using a wrapper that deletes itself from the sys.argv array like this:

del sys.argv[0]
exec(our_program)

This works on unix platform but not on windows because in def get_os_args() function the parameters are not read from sys.argv as is the standard but rather  from _get_windows_argv() and thus the deletion of the first item from argv is not being applied. Would it be possible to fix it?

**Comment by untitaker** [comment] 2016-03-30 17:38
How would you fix this?

**Comment by mitsuhiko** [comment] 2016-03-30 17:42
We already detect modifications to sys.argv I think, but only if they are performed after click's invocation. This sounds like such a specific usecase that you can just manually invoke click and pass the arguments in a way you want. Since this only affects profiling you will probably not care that much about broken unicode support there.

**Comment by stxlvt** [comment] 2016-04-21 11:54
I would like to add another case affected by this bug: debugging using Eclipse with PyDev doesn't work on Windows.

Minimal use case:

```
import click

@click.command()
def cli():
    print("testing")

if __name__ == "__main__":
    cli()
```

Now right-clicking on this file and selecting `debug as` => `python run` will result in the following error:

```
Error: no such option: --multiprocess
```

This is because the script is invoked like this by Eclipse:

```
C:\path\to\python.exe -u C:\Users\username\.p2\pool\plugins\org.python.pydev_4.4.0.201510052309\pysrc\pydevd.py
--multiprocess --print-in-debugger-startup --vm_type python --client 127.0.0.1
--port 0 --file C:\path\to\minimal_example_file.py
```

Click obviously attempts to parse the arguments for `pydevd` instead of the arguments it has prepared for the script in `sys.argv`.

I feel that this warrants a reconsideration on the _wontfix_ decision, since debugging a click script in Eclipse/PyDev should be considered a normal use case.

**Comment by untitaker** [comment] 2016-04-21 16:28
@stxlvt Your problem has a unrelated root cause.

I don't think there's a clean way to fix either.

**Comment by muikrad** [comment] 2016-04-26 15:45
I am facing this issue as well. I'm not sure why click wants to dive into Win32 calls to obtain the list of arguments, but doing so will probably prevent most "wrapper" functionalities to work correctly with click if the said wrapper needs to modify arguments before calling the Click script.

As others have mentionned, this prevents debugging from pycharm.

The comments say this:

> However if you are on Windows and running Python 2 the return value will actually be a list of unicode strings instead because the default behavior on that platform otherwise will not be able to carry all possible values that sys.argv can have.

Then the `_get_windows_argv()` uses the Win32API call to retrieve arguments and everything that was deleted by the wrapper script comes back to click, which errors out because of the unrelated arguments.

**Comment by muikrad** [comment] 2016-04-26 15:46
Would it be possible to compare the values of that Win32API call and the current sys.argv and remove the extra arguments?

**Comment by stxlvt** [comment] 2016-04-27 07:24
I suggest the following fix, which replaces the return statement of  `_get_windows_argv()`:

        # this import should be at the top of the file of course
        from collections import defaultdict 
        
        # Create an in-order list of candidate unicode translations
        # for each ascii string
        ascii_map = defaultdict(list)
        for arg in argv:
            ascii_map[arg.encode("ascii", errors="replace")].append(arg)
        
        # Put the first-appearing unicode alternative last to avoid pop(0)
        for v in ascii_map.values():
            v.reverse()
        
        # Translate sys.argv contents
        ret = []
        for arg in sys.argv[1:]:
            candidates = ascii_map[arg]
            if candidates:
                ret.append(candidates.pop())
            else:
                ret.append(arg)

        return ret

This works in almost all cases. The exception would be something like if the original arguments were

    xԸԸx xԺԺx

In this case, `sys.argv[1:]` would look like this:

    ['x??x', 'x??x']

If whoever modified sys.argv attempted to blindly swap these arguments, or do some other transformation on them that did not result in any actual change, then of course there would be no way for us to guess what modifications were attempted.

I've tested this on PyDev, and it allowed me to debug a script using click, and also accept unicode arguments with python 2.7.

If this change is accepted, then it seems that the `_initial_argv_hash` machinery is no longer needed. We can delete that variable, the `_hash_py_argv()` function, and change the body of `get_os_args` to

    if PY2 and WIN:
        # Attempt to translate sys.argv to unicode
        return _get_windows_argv()
    return sys.argv[1:]

By the way, this code in `_get_windows_argv()` could use a comment explaining why it's there and what it does.

        if not hasattr(sys, 'frozen'):
            argv = argv[1:]
            while len(argv) > 0:
                arg = argv[0]
                if not arg.startswith('-') or arg == '-':
                    break
                argv = argv[1:]
                if arg.startswith(('-c', '-m')):
                    break

It apparently removes options from the front of `argv` until it hits an argument, a single dash, or until the option is removed was `-c` or `-m`, but why it does this is hard to read from the code.

**Comment by jonapich** [comment] 2016-05-30 17:29
@stxlvt any chance of submitting a PR with that code if it works?

**Comment by tomas16** [comment] 2016-07-18 14:51
Same issue here, regular debugging session using PyCharm and Python 2.

`C:\Anaconda64\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 52392 --file C:/Users/TVandenHauwe/myscript.py
pydev debugger: process 13224 is connecting

Connected to pydev debugger (build 145.1504)
Error: no such option: --multiproc

Process finished with exit code 2`

**Comment by stxlvt** [comment] 2016-07-19 08:47
@jonapich Pull request [here](https://github.com/pallets/click/pull/615).

**Comment by alexwidener** [comment] 2016-12-01 23:37
Hi, @stxlvt and others - I just merged your pull request into our fork here: https://github.com/Pixomondo/click/tree/6.6.pxo.01 and it appears to have solved my issue with Pycharm debugging.

1: @stxlvt Thanks for working this out. The multiproc was annoying me in debugging for the last few days.
2: @untitaker /others perhaps we could take a look at the pull request since I was able to verify that it worked for my case? 

Thanks all!

**Comment by jonapich** [comment] 2017-02-10 15:06
The fixed worked for me as well! Can we get this merged and released? :D

**Comment by mitsuhiko** [comment] 2017-02-10 15:28
I don't understand the pull request so unlikely that i will pull this in. Can someone summarize the issue?

**Comment by mitsuhiko** [comment] 2017-02-10 15:29
To ask this in another way: since this only breaks in cases where some weird debugger is involved, why not pass the arguments explicitly in those cases?

**Comment by jonapich** [comment] 2017-02-10 16:07
I haven't dived into the technical aspects of this issue, but pycharm/eclipse launches pydev.py with a number of configuration options (such as --multiproc), which in turn runs your script (the one that uses click) with the options passed in explicitly.

During runtime, if you use the win32 call to check the arguments, you'll get them all. If you rely on sys.argv instead, you only get the ones relevant to your application.

As comparison, I have never had any problems with baker or argparse through pycharm, I guess they rely on sys.argv?

Here's the full command line from pycharm's debugging sessions:

C:\Python27\python.exe -B -E "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 61800 --file E:/test.py --some_arg=1 --some_other_arg=3

The script I'm trying to run is e:\test.py

**Comment by mitsuhiko** [comment] 2017-02-10 16:09
The reason we do not use `sys.argv` on windows is that it's broken for many unicode characters. You can pass `sys.argv` to the script already. You just pay for this by breaking part of the unicode support. I'm happy to find better workarounds but not sure which one will work best here.

**Comment by alexwidener** [comment] 2017-02-10 16:11
Completely understandable why you'd want the most possible support. And @jonapich explained it perfectly.

Just as a follow up, I've written more click apps since I last posted in December, and they've all worked flawlessly with the PR that I mentioned above.

**Comment by jonapich** [comment] 2017-02-10 16:13
I checked around pydevd.py and they do edit sys.argv explicitely, removing their extra arguments, before launching the script to debug, so that explains that.

@mitsuhiko is it possible to obtain some unicode bug scenarios that could be tested against this PR?

**Comment by mitsuhiko** [comment] 2017-02-10 16:15
@jonafato just pass an emoji from cmd.exe and try to print it.

**Comment by jonapich** [comment] 2017-02-10 16:45
My unicode/python knowledge is crap, please bear with me...

I can print ☺ if I hardcode it right in the script (but it appears as Γÿ║ in the console).

Passing it through click, I get this error:

```
UnicodeEncodeError: 'charmap' codec can't encode character u'\u263a' in position 0: character maps to <undefined>
```

I get the same behavior with and without the PR.

With baker or sys.argv, I get no errors but "?" is printed.

**Comment by mitsuhiko** [comment] 2017-02-10 16:47
What do you mean with print here? `print` does not support unicode on windows, only `click.echo` does. Secondly this is about getting the emoji entered into the cmd.exe and passing it as argument to sys.argv.

**Comment by jonapich** [comment] 2017-02-10 17:06
Nice! It works great, with and without the PR.

```
import click

@click.command()
@click.option("--char", type=click.STRING)
def main(char):
    click.echo(char)

if __name__ == '__main__':
    main()
```

Launched it as such using cmd.exe:

```
test.py --char ☺
```

Also tried using pycharm (with the PR):
```
C:\Python27\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 63800 --file E:/Projects/Repos/develop/pycoveo-deploy/wut.py --char ☺
pydev debugger: process 8228 is connecting

Connected to pydev debugger (build 163.10154.50)
☺

Process finished with exit code 0
```

Without the PR in pycharm:

```
C:\Python27\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 63838 --file E:/Projects/Repos/develop/pycoveo-deploy/wut.py --char ☺
pydev debugger: process 12956 is connecting

Connected to pydev debugger (build 163.10154.50)
Error: no such option: --multiproc

Process finished with exit code 2
```

**Comment by mitsuhiko** [comment] 2017-02-10 17:18
Note that `☺` is not an emoji. `😍` is one.

**Comment by jonapich** [comment] 2017-02-10 17:21
No PR:

```
C:\Python27\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 64288 --file E:/Projects/Repos/develop/wut.py --char 😍
pydev debugger: process 12248 is connecting

Connected to pydev debugger (build 163.10154.50)
Error: no such option: --multiproc

Process finished with exit code 2
```

PR:

```
C:\Python27\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 64318 --file E:/Projects/Repos/develop/wut.py --char 😍
pydev debugger: process 3468 is connecting

Connected to pydev debugger (build 163.10154.50)
😍

Process finished with exit code 0
```

**Comment by jonapich** [comment] 2017-02-10 17:23
And through cmd.exe, I get the same result with and without PR:
```
E:\Projects\Repos\develop\pycoveo-deploy>wut --char 😍
😍
```

**Comment by untitaker** [comment] 2017-02-10 17:23
When the debugger passes `--multiproc` to the Click CLI, then there's a bug in the debugger and not Click.

**Comment by mitsuhiko** [comment] 2017-02-10 17:25
@jonafato what codepage is your shell in?

**Comment by mitsuhiko** [comment] 2017-02-10 17:26
For what it's worth on 2.7 it's impossible for emojis to roundtrip without our custom unicode api handling unless the shell is in the utf-8 codepage.

**Comment by jonapich** [comment] 2017-02-10 17:31
@untitaker the debugger removes the --multiproc from arg.sysv (along with all others), the problem is that click uses the win32 api to get the arguments, the debugger can't do anything about that.

**Comment by jonapich** [comment] 2017-02-10 17:34
@mitsuhiko you keep pinging the wrong guy, i'm not fato ;)

My shell uses codepage 437. The emoji doesn't actually print correctly, but when I copy/paste it to github, the emoji comes back.

![image](https://cloud.githubusercontent.com/assets/5009356/22837122/3af711e8-ef8d-11e6-9d4e-d8b1d6fc3997.png)

**Comment by mitsuhiko** [comment] 2017-02-10 18:20
I need to look at this again on windows. Effectively click is — as far as possible — using unicode APIs on windows to make this work as good as possible. The issue here is when other stuff modifies `sys.argv` which is limited to the current codepage on windows.

**Comment by copernico** [comment] 2017-03-20 09:14
Can someone summarize what the current options are for debugging scripts that use click?
My experience is that neither PyDev nor PyCharm work with 'plain' click. While a proper fix is not available, is there a workaround (except applying the PR discussed above)?

**Comment by mitsuhiko** [comment] 2017-03-20 09:53
@copernico you can just invoke click with `sys.argv` as parameter and it will disable the unicode handling.

**Comment by copernico** [comment] 2017-03-21 22:29
Thanks @mitsuhiko ; but could you share a basic example of how to do that? I'm confused because I don't ever invoke click itself in my scripts, I only use the annotations provided by click, so I'm not sure to which function I should pass sys.argv as a parameter.

**Comment by mitsuhiko** [comment] 2017-03-21 22:32
```python
import sys
import click

@click.command()
def foo():
 pass

foo(sys.argv[1:])
```

**Comment by copernico** [comment] 2017-03-21 22:36
Excellent, that worked for me (actually, I pass the parameter to a function annotated as @click.group, but that works the same). Thanks for the prompt reply!

**Comment by int19h** [comment] 2019-07-11 19:58
> When the debugger passes `--multiproc` to the Click CLI, then there's a bug in the debugger and not Click.

@untitaker, to clarify, the debugger is not actually passing `--multiproc` to the Click CLI in this case. It's a switch that is passed to the debugger itself, which precedes the part of the command line that actually invokes the app. Something like this:
```
python -m pydevd --multiproc ... --file myscript.py --foo
```
The debugger then removes those bits from `sys.argv` before it starts running the app, and expects the app to use the modified `sys.argv`, which by then looks like:
```
["myscript.py", "--foo"]
```
i.e. essentially the debugger here does something very similar to what the Python interpreter binary itself does, in treating the command line up to `foo.py` or `-m foo` as switches for Python, and command line from there on as switches for the app.

But because Click on py2.7-win32 retrieves command line via OS facilities, it ignores this rewriting, and instead treats `--multiproc` as if it were passed to myscript.py.

Note that per #655, the stock `pdb` has the same exact problem. Among third party debuggers, aside from pydevd, it also affects https://github.com/microsoft/ptvsd.

In general, this affects any Python tool that invokes some generic Python script or module after processing its own command line switches in a manner similar to Python itself. Whenever said script or module uses Click, and does not explicitly pass `sys.argv`, things break on py2.7-win32. E.g. see https://github.com/pallets/flask/issues/3297 for an example of Flask (briefly) affected by this.

Thus, it is not always possible for the end user to use the workaround with explicit `sys.argv` parsing - because the command line parsing might not be in their own code at all; it can be in a third-party package that they simply depend on.

**Comment by jcrotts** [comment] 2021-02-27 20:07
I don't have PyCharm around to test, but I'm assuming that like [#655 ](https://github.com/pallets/click/issues/655), this is also a Python 2 only issue. If someone has a test case where this is happening on Python 3 please post it and I'll reopen the issue.

**Closed by jcrotts** 2021-02-27 20:07 UTC
Labels: windows
