### ISSUE TITLE
Same dest name flag_value and type not working.

### ISSUE THREAD

**Issue by no1xsyzy** [pallets/click#1688] opened 2020-10-12 17:47 UTC
### Expected Behavior

Tell us what should happen.

```python
import os, click

@click.command()
@click.option('--output-stdout', 'output', flag_value='-')
@click.option('--output-default', 'output', flag_value='/path/to/default/output/location')
@click.option('-o', '--output', type=click.File('w'), default=None)
def edit(output):
    click.echo(type(output))
    click.echo(output)

edit()
```

with `--output` option, the provided string should be (lazily) opened.

```ShellSession
$ python e.py --output /path/to/file
<class 'click.utils.LazyFile'>
<unopened file '/path/to/file' w>
```

### Actual Behavior

Instead, it is still `str`

```ShellSession
$ python e.py --output /path/to/file
<class 'str'>
/path/to/file
```

Although `--output-stdout` and `--output-default` works as expected.

```ShellSession
$ python e.py --output-default
<class 'click.utils.LazyFile'>
<unopened file '/path/to/default/output/location' w>
$ python e.py --output-stdout
<class '_io.TextIOWrapper'>
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
```

But if I put them after `--output`, they will not work too.

### Environment

* Python version: Python 3.8.6
* Click version: click==7.1.2

**Comment by davidism** [comment] 2020-10-12 18:38
Essentially a duplicate of https://github.com/pallets/click/issues/1682. I suggest using a custom type rather than trying to combine a bunch of options under the same name, which I don't think is documented to work anywhere.

**Closed** 2020-10-12 23:27 UTC

**Comment by no1xsyzy** [comment] 2020-10-13 17:57
Because it just makes sense? Stored into `output` and then process with the type

`type` of last unused option or the last used option if all used takes effect. Notice that `flag_value` with `default=True` doesn't work well (results in `str`). So I finally manage to do so with a processor at the end of all of them. For example:
```python
import click


@click.command()
@click.option('-o', '--output', metavar='FILENAME', help="set output file location to any location")
@click.option('--output-place-one', 'output', flag_value='/place/one', help="set output file to /place/one")
@click.option('--output-place-two', 'output', flag_value='/place/two', help="set output file to /place/two")
@click.option('--output-*\'s can be used to:', 'output', type=click.File('w'),
              help="set output file to predefined location",
              default='/place/default', show_default=True, metavar="")
def edit(output):
    click.echo(f"{type(output)=}")
    click.echo(f"{output=}")
    click.echo("-----")


edit()
```

```console
$ python e.py
type(output)=<class 'click.utils.LazyFile'>
output=<unopened file '/place/default' w>
$ python e.py --output-place-one
type(output)=<class 'click.utils.LazyFile'>
output=<unopened file '/place/one' w>
$ python e.py --output-place-two
type(output)=<class 'click.utils.LazyFile'>
output=<unopened file '/place/two' w>
$ python e.py --help
Usage: e.py [OPTIONS]

Options:
  -o, --output FILENAME          set output file location to any location
  --output-place-one             set output file to /place/one
  --output-place-two             set output file to /place/two
  --output-*'s can be used to:   set output file to predefined location
                                 [default: /place/default]

  --help                         Show this message and exit.
```

Also, specify `hidden=True` can just hide it. I also made the name hard to invoke from shell. But I'm not sure if there is a way to make it totally uninvokable.

**Comment by davidism** [comment] 2020-10-13 18:11
You're trying to be too clever. This is not a supported use case. As stated above, use a custom type if you want custom processing, rather than trying to have options overwrite each other (which depends on both the definition order and the order they're given on the command line).
