### ISSUE TITLE
Options with custom type and default value seems broken in 8.0.x

### ISSUE THREAD

**Issue by iceman-11** [pallets/click#1951] opened 2021-06-08 13:43 UTC
When creating a 'click.option' with a custom type and a default value, the convert() method of the custom type is called incorrectly twice when the default is used.

Here is a simple code sample that works well on click 7.1.2 but fails on 8.0.1:
```
import re
import click
import logging

from dataclasses import dataclass
from click import Context, Parameter
from typing import Optional

logging.basicConfig()

log = logging.getLogger(__package__)
log.setLevel(logging.DEBUG)


@dataclass
class Foo:
    bar: str


class FooOption(click.ParamType):
    name = "foo"

    def convert(
        self, value: str, param: Optional[Parameter], ctx: Optional[Context]
    ) -> Optional[Foo]:
        log.debug(f"value = {value!r}")
        log.debug(f"param = {param!r}")
        log.debug(f"ctx   = {ctx!r}")

        if value is None:
            return None

        try:
            if re.match(r"^ba[rz]$", value):
                return Foo(bar=value)
            else:
                self.fail(f"Bad option: {value!r}", param, ctx)
        except re.error as e:
            self.fail(str(e), param, ctx)


@click.command()
@click.option(
    "--foo",
    type=FooOption(),
    default="bar"
)
def main(foo: Foo):
    print(f"-> {foo!r}")


if __name__ == "__main__":
    main()
```

In Click 7.1.2 (which is working as expected), whether we use the option or fallback to the default, the convert method of the `FooOption` is only called once.
```
(venv) $ python click-bug.py --foo baz
DEBUG:root:value = 'baz'
DEBUG:root:param = <Option foo>
DEBUG:root:ctx   = <click.core.Context object at 0x000002D49E0DEC70>
-> Foo(bar='baz')

(venv) $ python click-bug.py
DEBUG:root:value = 'bar'
DEBUG:root:param = <Option foo>
DEBUG:root:ctx   = <click.core.Context object at 0x0000017D600AEC70>
-> Foo(bar='bar')
```

In Click 8.0.1, if we specify the option on the CLI, it works fine.
But if we use the default, the convert method is called twice, once with the `str` value as expected but then a second time with the object that we generated in the first call. Which, in the case of the example above, cause the regular expression match to generate a `TypeError` exception as we do not expect to get a `Foo` object there.

```
(venv) $ python click-bug.py --foo baz
DEBUG:root:value = 'baz'
DEBUG:root:param = <Option foo>
DEBUG:root:ctx   = <click.core.Context object at 0x0000013D11D35A30>
-> Foo(bar='baz')

(venv) $ python click-bug.py
DEBUG:root:value = 'bar'
DEBUG:root:param = <Option foo>
DEBUG:root:ctx   = <click.core.Context object at 0x000002B7DB865A30>
DEBUG:root:value = Foo(bar='bar')
DEBUG:root:param = <Option foo>
DEBUG:root:ctx   = <click.core.Context object at 0x000002B7DB865A30>
Traceback (most recent call last):
  File "C:\PAC\devel\python\test\click-bug.py", line 53, in <module>
    main()
  File "C:\PAC\devel\python\test\venv\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\PAC\devel\python\test\venv\lib\site-packages\click\core.py", line 1061, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\PAC\devel\python\test\venv\lib\site-packages\click\core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "C:\PAC\devel\python\test\venv\lib\site-packages\click\core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\PAC\devel\python\test\venv\lib\site-packages\click\core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "C:\PAC\devel\python\test\venv\lib\site-packages\click\core.py", line 2320, in process_value
    value = self.type_cast_value(ctx, value)
  File "C:\PAC\devel\python\test\venv\lib\site-packages\click\core.py", line 2307, in type_cast_value
    return convert(value)
  File "C:\PAC\devel\python\test\venv\lib\site-packages\click\types.py", line 75, in __call__
    return self.convert(value, param, ctx)
  File "C:\PAC\devel\python\test\click-bug.py", line 34, in convert
    if re.match(r"^ba[rz]$", value):
  File "C:\Users\slambert\AppData\Local\Programs\Python\Python39\lib\re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

Environment:

- Python version: 3.9.5 (on Windows 10 64-bit)
- Click version: 8.0.1

**Comment by davidism** [comment] 2021-06-08 13:46
Duplicate of #1898

**Closed by davidism** 2021-06-08 13:46 UTC
