### ISSUE TITLE
Documentation sidebar overflows onto main text

### ISSUE THREAD

**Issue by sandalwoodbox** [pallets/click#2502] opened 2023-04-30 16:57 UTC
Browser: Chrome, Mac OS
Link: https://click.palletsprojects.com/en/8.1.x/api/#click.version_option

![Screen Shot 2023-04-30 at 9 56 00 AM](https://user-images.githubusercontent.com/80227316/235365941-dc05d97e-4249-4dd9-9ac6-197d52e77d2b.png)

This is just the example I ran into - happens in other spots as well. Makes things a little hard to read.

**Comment by davidism** [comment] 2023-04-30 16:58
Duplicate of https://github.com/pallets/pallets-sphinx-themes/issues/64

**Closed by davidism** 2023-04-30 16:58 UTC

**Comment by sandalwoodbox** [comment] 2023-04-30 17:18
@davidism it looks like that issue is closed as resolved; does that mean there's additional work on the click side to upgrade to a newer version of the theme?
