### ISSUE TITLE
path completion in bash not working

### ISSUE THREAD

**Issue by DEvil0000** [pallets/click#1945] opened 2021-06-02 12:36 UTC
My understanding is, that `click.File` and `click.Path` completion should be working as a new feature with version 8.0.x. For me it is however not working.

Simple test programm I used:
```
#cat test_path 
#!/usr/bin/python3

import click

@click.group()
def test_path():
  pass

@test_path.command()
@click.argument('path', nargs=1, type=click.Path())
def arg(path):
  print(path)

@test_path.command()
@click.option('--path', type=click.Path(), help='test option path complete')
def opt(path):
  print(path)

if __name__ == '__main__':
    test_path()
```
Of course I executed `eval "$(_TEST_PATH_COMPLETE=bash_source test_path)"` and get completion in general but not for a path (and likely also not for files).

Completion I get:
```
test_path\t\t  -> arg opt
test_path arg\t\t -> .hidden_File_in_local_dir file_in_local_dir more_files
test_path arg .\t\t -> <nothing>
test_path arg /\t\t -> <nothing>
test_path arg ./\t\t -> <nothing>
test_path opt --path\t\t -> .hidden_File_in_local_dir file_in_local_dir more_files
test_path opt --path .\t\t -> <nothing>
test_path opt --path /\t\t -> <nothing>
test_path opt --path ./\t\t -> <nothing>
```

Expected is:
```
test_path arg .\t\t -> .hidden_File_in_local_dir
test_path arg f\t\t -> file_in_local_dir
test_path arg /\t\t -> /root /home /usr /tmp <...>
test_path arg ./\t\t -> ./local_dir
test_path opt --path .\t\t -> .hidden_File_in_local_dir
test_path opt --path f\t\t -> file_in_local_dir
test_path opt --path /\t\t -> /root /home /usr /tmp <...>
test_path opt --path ./\t\t -> ./local_dir
```

As a additional note: I think it always uses `file` instead of `path` completion mode and that only for the double tab after command completion with empty incomplete string.

Environment:

- Ubuntu: 20.04
- Python version: 3.8.5
- Click version: 8.0.1

**Comment by davidism** [comment] 2021-06-02 14:01
Duplicate of #1929

**Closed by davidism** 2021-06-02 14:01 UTC
