### ISSUE TITLE
Add click.Path option that allows checking for executable flag

### ISSUE THREAD

**Issue by blsqr** [pallets/click#2192] opened 2022-02-14 10:56 UTC
[`click.Path`](https://click.palletsprojects.com/en/8.0.x/api/#click.Path) already allows checking whether a path points to a directory ( `dir_okay`) or a file ( `file_okay`) and whether it is `readable` and/or `writeable`. I would suggest to add an additional `executable` flag that would check if the executable bit is set for the file or directory the path points to.

This surely can be achieved via a custom type, but it seems to me that this would be a valuable extension of `click.Path` as it would lead to all three access modes being checkable via click.  
I am happy to contribute to an implementation, if there is any interest in this.

**Comment by davidism** [comment] 2022-02-21 21:36
Duplicate of #1961

**Closed by davidism** 2022-02-21 21:36 UTC

**Comment by blsqr** [comment] 2022-02-22 08:06
Ah, I missed that one, sorry! 👍
