### ISSUE TITLE
Required options on parent command break --help on child commands

### ISSUE THREAD

**Issue by srjturner** [pallets/click#814] opened 2017-06-30 10:35 UTC
I have a command which has a required option, and sub-command(s):

```
@click.group()
@click.option('-f', '--foo', required=True, help='The foo')
@click.pass_context
def cli(ctx, foo):
    ctx.obj = {'foo': foo}
    print("cli, ctx.obj  = {}".format(ctx.obj))

@cli.command()
@click.option('-b', '--bar', help="The bar")
@click.pass_obj
def child(context, bar):
    print("aws, context = {}, bar = {}".format(context, bar))
```
If I use help on the top-level command then I get the expected text, and the fact that it requires the 'foo' option is not a problem:

```
> python example.py  --help
Usage: example.py [OPTIONS] COMMAND [ARGS]...

Options:
  -f, --foo TEXT  The foo  [required]
  --help          Show this message and exit.

Commands:
  child
```

However, if I do help on the child command, I get an error unless I supply the parent's required option:

```
> python example.py child --help
Usage: example.py [OPTIONS] COMMAND [ARGS]...

Error: Missing option "-f" / "--foo".
```

Given that I am only invoking the (implicit) --help option of the child command, why does click still enforce the required on the parent command? Is it because the parent command actually fires when anything on the child is run *including help*? Is there any workaround (other than not using required or moving the options from the parent to each child)?

**Comment by keshabb** [comment] 2017-08-28 15:19
I ran into same problem too

**Comment by reyx7** [comment] 2018-03-04 21:00
The same problem to , any solutions ??

**Comment by dagostinelli** [comment] 2018-05-17 13:08
I have this issue too.  In my parent, there is a prompt for username/password.  But when the user invokes help on a child, it asks for the username/password, which is frustrating.

Intuitive:
```
$ python myapp.py child
What is your username: bob
<app does something>
```

Not-Intuitive:
```
python myapp.py child --help
What is your username: bob
Usage: myapp child [OPTIONS] COMMAND [ARGS]...
<snip>
```

Sample Code:

```
import click

# http://click.pocoo.org/5/options/
def abort_if_false(ctx, param, value):
	if not value:
		ctx.abort()

@click.group()
@click.option('--username', envvar='MYAPP_USERNAME', prompt="What is the username", required=True)
@click.pass_context
def myapp(ctx, username):
	"""MyApp
	
	Lorem ipsum dolor
	"""
	ctx.obj = username
	click.echo('I am about to invoke %s' % ctx.invoked_subcommand)

@myapp.command()
@click.option('--yes', is_flag=True, callback=abort_if_false, expose_value=False, prompt="Are you sure that you want to delete?", help="No confirmation. Just go")
def delete():
	click.echo('deleted')

if __name__ == '__main__':
	myapp()

```

**Comment by dagostinelli** [comment] 2018-05-18 02:12
This may also be related to #353 and #295.

There is a work around in #295 that may also help some of us on this thread while we wait for a more complete solution.

**Comment by espdev** [comment] 2019-12-02 18:05
Referring to #295 and my experiments I can say this is a fundamental issue of nested commands architectural design in Click.

For example we can write the following code:
```python
# app.py

@click.group()
@click.option('--hello')
def cli(**params):
    print('"cli" was invoked with params:', params)

@cli.command()
@click.option('--foo')
def sub(**params):
    print('"sub" was invoked with params:', params)

cli()
```

If we call `--help` for sub-command `sub` the main `cli` callback will be invoked anyway. We will see the following output:
```
$ python app.py sub --help
"cli" was invoked with params: {'hello': None}
Usage: app2.py sub [OPTIONS]

Options:
  --foo TEXT
  --help      Show this message and exit.
```

It is wrong behavior. The main command should not be called and its arguments should not be processed if we call a sub-command with `--help` argument or any other argument that forced shuts down the application before it will doing anything. And this behavior is not described in the documentation: https://click.palletsprojects.com/en/7.x/commands/#passing-parameters

I'm surprising the critical error is so old and hasn't been fixed yet.

**Comment by davidism** [comment] 2019-12-02 18:09
> It is wrong behavior.

It's not "wrong", it just "is". Given the dynamic nature of Click, it's not possible to guarantee a sub-command is reachable and will behave consistently without evaluating the chain of commands and options up to it.

> I'm surprising the critical error is so old and hasn't been fixed yet.

PRs welcome.

**Comment by espdev** [comment] 2019-12-02 18:28
> Given the dynamic nature of Click, it's not possible to guarantee a sub-command is reachable and will behave consistently without evaluating the chain of commands and options up to it.

You are right, but this issue can affect many cli tools which contain required/prompt/interact options (without default values) in the parent commands. If a user just wants to see help for nested commands they cannot do it.

> PRs welcome.

I would be glad, but seems it will required to rewrite a half of Click. :)
https://github.com/pallets/click/issues/295#issuecomment-122708864

**Comment by davidism** [comment] 2019-12-02 18:40
> I would be glad, but seems it will required to rewrite a half of Click. :)

Then why are you "surprised the critical error is so old and hasn't been fixed yet"?

**Comment by davidism** [comment] 2019-12-02 18:40
Duplicate of #295

**Closed by davidism** 2019-12-02 18:40 UTC
Labels: bug
