### ISSUE TITLE
Options of type click.File ignore a default value given as a string (?)

### ISSUE THREAD

**Issue by s-m-e** [pallets/click#1215] opened 2019-02-01 10:05 UTC
- CPython 3.6.6
- click 7.0
- x86_64 Linux

This could be an unusual edge case and I find it hard to describe ... so let's start with an MVE. The following is saved into `test.py`:

```python
import click

@click.command()
@click.option(
	'--logfile', '-l',
	default = 'default.json', type = click.File('r'), show_default = True,
	multiple = True, required = True,
	help = 'name of input log file, can be specified multiple times',
	)
def test(logfile):
	for f in logfile:
		click.echo(f.read())

if __name__ == '__main__':
	test()
```

Here is what happens with the above script in a shell:

```bash
(env) user@box:~/demo> python test.py --help
Usage: test.py [OPTIONS]

Options:
  -l, --logfile FILENAME  name of input log file, can be specified multiple
                          times  [default: default.json; required]
  --help                  Show this message and exit.
(env) user@box:~/demo> ls -lah
insgesamt 63M
drwxr-xr-x 2 user users 4,0K  1. Feb 10:45 .
drwxr-xr-x 9 user users 4,0K  1. Feb 09:32 ..
-rwxr-xr-x 1 user users  341  1. Feb 10:45 test.py
(env) user@box:~/demo> python test.py
Usage: test.py [OPTIONS]
Try "test.py --help" for help.

Error: Invalid value for "--logfile" / "-l": Could not open file: d: No such file or directory
(env) user@box:~/demo> touch default.json
(env) user@box:~/demo> ls -lah
insgesamt 63M
drwxr-xr-x 2 user users 4,0K  1. Feb 10:45 .
drwxr-xr-x 9 user users 4,0K  1. Feb 09:32 ..
-rw-r--r-- 1 user users    0  1. Feb 10:45 default.json
-rwxr-xr-x 1 user users  341  1. Feb 10:45 test.py
(env) user@box:~/demo> python test.py
Usage: test.py [OPTIONS]
Try "test.py --help" for help.

Error: Invalid value for "--logfile" / "-l": Could not open file: d: No such file or directory
(env) user@box:~/demo> python test.py -l default.json

(env) user@box:~/demo>
```

My script is supposed to accept one or more `-l` options, pointing to existing files. If the user does not specify `-l`, a default file name is supposed to be opened. The options rely on `click.File`. In the above context, the option apparently ignores its default value (default file name). Sometimes it tells me `Could not open file: d: No such file or directory`, sometimes it tells me `Could not open file: b: No such file or directory` (notice the difference between `b` and `d`).

I guess an option of type `click.File` has no concept of dealing with a string as default (?).

**Comment by doobeh** [comment] 2019-05-05 23:37
You've set `multiple` to True-- which means your default variable is going to assumed to be an iterable (ideally a list of filenames in your example) but because you've just given it a string (which is iterable character by character) you're getting the no such file error, because instead of trying to open `default.json` it's iterating over that string and in so, trying to open `d`.

Changing `default = 'default.json',` to `default = ['default.json'],` clears up your problem.

**Comment by jcrotts** [comment] 2019-05-24 19:10
Closing this because it is not a bug, thanks for answering @doobeh .

**Closed by jcrotts** 2019-05-24 19:10 UTC
