### ISSUE TITLE
Implicit order of choosing parameter names changed in 6.x, but still inconsistent with documentation

### ISSUE THREAD

**Issue by amiryal** [pallets/click#1147] opened 2018-10-15 14:04 UTC
From [the documentation](https://github.com/pallets/click/blob/2e856a5281a29eb4293059b37427643c3d52a19a/docs/parameters.rst#parameter-names):
> If all names for a parameter contain dashes, the internal name is generated automatically by taking the longest argument and converting all dashes to underscores.

However, in the implementation, when the possible names are sorted, it’s only for the purpose of grouping them “long options first” — meaning “options with two dashes first”, not “longest name first”.

See current master: https://github.com/pallets/click/blob/2e856a5281a29eb4293059b37427643c3d52a19a/click/core.py#L1641
And compare with branch 5.x: https://github.com/pallets/click/blob/7ede2dbe5ca3bd291c7d18f7767f10752496c6ae/click/core.py#L1506

Between version 5.x and 6.x, the implicit (misdocumented) order had changed, which broke my script.

This bug manifests only when multiple long parameter (option) names are specified, i.e.:
```python
@click.option('--shorter', '--longer-option')
```
…in which case different versions of Click would choose a different name between `shorter` and `longer_option` instead of always choosing `longer_option` as suggested in the documentation.

**Comment by davidism** [comment] 2018-10-15 14:18
Duplicate of #1140

**Closed by davidism** 2018-10-15 14:18 UTC
