### ISSUE TITLE
Print the required parameters at the very beginning of `--help` output

### ISSUE THREAD

**Issue by pbeza** [pallets/click#1993] opened 2021-07-06 12:03 UTC
I would like to be able to specify that I want `--help` to print `required` params in the very beginning. This helps UX, especially when there are many options and only a few of them are required.

### Code

```python
#!/usr/bin/env python3

import click

@click.command()
@click.option('--boolean-opt/--no-boolean-opt', default=False, help='Boolean opt')
@click.option('--first-not-required', required=False, help='First not required')
@click.option('--first-required', required=True, help='First required')
@click.option('--second-not-required', required=False, help='Second not required')
@click.option('--second-required', required=True, help='Second required')
@click.option('--third-not-required', required=False, help='Third not required')
@click.option('--third-required', required=True, help='Third required')
def info(**args):
    pass


if __name__ == '__main__':
    info()
```

### What I get

```console
$ python3 ./test.py --help
Usage: test.py [OPTIONS]

Options:
  --boolean-opt / --no-boolean-opt
                                  Boolean opt
  --first-not-required TEXT       First not required
  --first-required TEXT           First required  [required]
  --second-not-required TEXT      Second not required
  --second-required TEXT          Second required  [required]
  --third-not-required TEXT       Third not required
  --third-required TEXT           Third required  [required]
  --help                          Show this message and exit.
```

### Expected output

```console
$ python3 ./test.py --help
Usage: test.py [OPTIONS]

Options:
  --first-required TEXT           First required  [required]
  --second-required TEXT          Second required  [required]
  --third-required TEXT           Third required  [required]
  --boolean-opt / --no-boolean-opt
                                  Boolean opt
  --first-not-required TEXT       First not required
  --second-not-required TEXT      Second not required
  --third-not-required TEXT       Third not required
  --help                          Show this message and exit.
```

I'm not sure where is the best place to pass an information to `click` to reorder options in `--help` output. Maybe:

```python
@click.command(required_first=True)
```
?

Alternatively:

```python
@click.command(opts_help_order=HelpOptionsOrder.REQUIRED_FIRST)
```

if you want to add more ordering options in the future (e.g. `HelpOptionsOrder.ALPHABETICAL_ORDER`, `custom_handler`).

**Comment by davidism** [comment] 2021-07-07 15:14
Duplicate of #561

**Closed by davidism** 2021-07-07 15:14 UTC
