### ISSUE TITLE
Better control of reflowing for lists

### ISSUE THREAD

**Issue by schollii** [pallets/click#1218] opened 2019-02-03 19:31 UTC
It would be nice to be able to define lists in long-help text. Example output: 
```
Usage: .... FORMAT arg

Set the format of blabla. The FORMAT arg can be any combination of: 

- %s: asdfasdf as df asfd as df asdf 
   asdfasdfasfdasdf asdf asdf asdf asdf 
- %a: xcv xzcv  vz xcv zx cvz xcv zxcv zxcv
   zc vz xcv zxc v zxcv zx cvz xvc 

Here are the steps to upgrade the system according to the new format: 
1. Define format
2. Use new format
...
```

Currently it is not possible to do this, instead you can only do this: 
```
Set the format of blabla. The FORMAT arg can be any combination of: 

- %s: asdfasdf as df asfd as df asdf 
asdfasdfasfdasdf asdf asdf asdf asdf 

- %a: xcv xzcv  vz xcv zx cvz xcv zxcv zxcv
zc vz xcv zxc v zxcv zx cvz xvc 
```
i.e each list item is a paragraph and it does not get indented as list items would AND you need blank lines otherwise the list items end up all merged into one paragraph. 

I just noticed that the Options help section that Click generates already does something similar for options, so the functionality is already there to do the re-wrapping, but the Formatter just needs to be extended to trap list-start/list-end and call upon that piece of code that currently handles Options formatting. If you have any pointers I can give this a shot.

**Comment by davidism** [comment] 2019-02-03 20:19
Duplicate of #561 

I'm not sure what Click could reasonably do here. It doesn't have an understanding of text markup, it just sees a string with newlines.

If you could be more specific about how the options formatting is related to this, that might help clarify what you think could be changed.

**Comment by schollii** [comment] 2019-02-04 03:49
What I mean is that if I write a docstring like this: 
```
@click.command()
def my_cmd():
   """
   Something:
   - item 1: aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa 
   - item 2: bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb 
   """
```
the output of `my_cmd --help`  should be
```
Usage: my_cmd ....
   Something:
   - item 1: aaa aaa aaa aaa aaa aaa aaa aaa aaa 
      aaa aaa aaa 
   - item 2: bbb bbb bbb bbb bbb bbb bbb bbb 
     bbb bbb bbb 
```
Compare this to an Options section: 
```
Options:
  -n, --name1 TEXT   asdfasdfas dfasdfasdfas dfasdfsadf adsfa sdf as dfasdf
                     asfd as df asdf asdf asd fas df asdf as dfa sdf asdf as
                     df
  -n2, --name2 TEXT  asdfasdfas dfasdfasdfas dfasdfsadf adsfa sdf as dfasdf
                     asfd as df asdf asdf asd fas df asdf as dfa sdf asdf as
                     df
```
this properly wraps the option help text: the first line of -n option is indented 2 spaces and the next 2 lines are indented by 20; the same for `-n2` option. The exact same code could handle a list item. E.g. say you have a function `format_option(option_text, help, width, first_indent, subsequent_indent)`, called like this:
```
formatted = format_option("-n, --name1 TEXT", "asdfasdfas ...", 80, 2, 20)
```
An unnumbered  list item could be printed via the same call like this
```
formatted = format_option("-", "asdfasdfas ...", 80, 2, 4)
```
and a numbered list too:
```
formatted = format_option("1.", "asdfasdfas ...", 80, 2, 5)
```
The Formatter just needs to give the "string with a bunch of newlines" to a `reflow(lines)` function instead of giving to (I presume) `textwrap.fill`. Something like (pseudocode):
```
class Formatter:
    ....
    reflowed_lines = reflow(docstring)
    print(reflowed_lines)
    ...

def reflow(lines):
    lines = lines.split('\n')
    reflowed_lines = []
    group = []
    state = paragraph  # state enum
    for line in lines.split('\n'):
        if state == paragraph:
            if is_list_item(line):
                reflowed_lines.extend( textwrap.fill(group, width, 2, 4) )
                state = list_item
                offset = len(list_item_prefix(line))
                group=[line[offset:]]
            else:
                group.append(line)

        elif state == list_item:
            if is_list_item(line) or is_blank_line(line):
                reflowed_lines.extend( format_options('-', group, width, 2, 4) )
                if is_blank_line(line):
                    state = paragraph
                    group = ['\n']
                else:
                    offset = len(list_item_prefix(line))
                    group = [line[offset:]]
            else:
                group.append(line)
                
    if state == paragraph:
        reflowed_lines.extend( textwrap.fill(group, width, 2, 4) )
   else: # state is list_item
        reflowed_lines.extend( format_options('-', group, width, 2, 4) )

    return '\n'.join(reflowed_lines)
```

**Comment by davidism** [comment] 2019-02-04 04:03
The options are individual strings though, it's easy to know what to wrap. The docstring is just one big string, and Click makes no assumptions about its content besides "two newlines means paragraph".

We would have to implement a parser that analyzed the docstring and understood things like "leading '-' means bullet point, do something special". The actual implementation of such a parser is out of scope for Click. #561 proposes making the formatter overridable so it's possible for someone to implement.

**Comment by schollii** [comment] 2019-02-04 20:36
I've done this sort of stuff before, there is no need to implement a
parser, we're not talking markdown here, just lists! :)  I'll send you an
implementation of the reflow function and you can try it out. Just give me
a few days.

**Comment by davidism** [comment] 2019-02-04 20:45
"Just lists" I don't want to add any parsing to the formatter at all.

**Comment by schollii** [comment] 2019-02-04 23:48
Please check https://github.com/schollii/sandals/blob/master/reflow.py and let me know what you think. It will be quite easy to make it handle other list item patters like * and numbers

**Comment by davidism** [comment] 2019-02-09 13:30
Thanks for the implementation example. I think that would definitely work once we have #561, but I don't want to add it straight to Click, as it special cases only one type of formatting.

**Closed by davidism** 2019-02-09 13:30 UTC

**Comment by davidism** [comment] 2019-02-09 13:40
You can probably also implement this by overriding `Command.format_help_text` to apply the extra formatting.

**Comment by schollii** [comment] 2019-02-09 17:07
Thanks for the info. 

I looked at format_help_text and that led me to your _textwrap.TextWrapper class that derives from textwrap.TextWrapper. I think it would be sufficient to override the fill() method (the following is a hack around your TextWrapper being "private": 
```
class MyTextWrapper(click._textwrap.TextWrapper):
    def fill(self, text):
        ...

click._textwrap.TextWrapper = MyTextWrapper
```
So if you exposed your TextWrapper as click.TextWrapper, and had like a `click.setTextWrapperClass(cls)` where cls is a class that derives from click.TextWrapper, then we could do this:
```
class MyTextWrapper(click.TextWrapper):
    def fill(...):
        ...

click.setTextWrapperClass(MyTextWrapper)
```
Seems like just a few lines of code change would be necessary, what do you think?

**Comment by davidism** [comment] 2019-02-09 19:26
#938
