### ISSUE TITLE
Extended helptext customization

### ISSUE THREAD

**Issue by nothead31** [pallets/click#1995] opened 2021-07-06 19:16 UTC
I'm looking for a more robust helptext system, which the documentation says currently doesn't exist. For example, in the project I am working on, I get this excerpt when typing cli.py -h (a placeholder name for the script):

```
Usage: cli.py [OPTIONS] TRANSLATOR

  Use TRANSLATOR to translate source material into another language.
 ...

Options:
  -src, --source TEXT   source language to translate from  [required]
  -tgt, --target TEXT   target language to translate to  [required]
 <snip>
```

What I would like to be able to do is format the helptext as:

```
Usage: cli.py TRANSLATOR [-src | --source] [-tgt | --target]

  Use TRANSLATOR to translate source material into another language.
 ...

Required Options:
  -src, --source TEXT   source language to translate from
  -tgt, --target TEXT   target language to translate to
Optional arguments:
  <snip>
Flags:
<snip>
 -h, --help            Show this message and exit.
```

Or otherwise allowing a more robust and customizable helptext generator. The particular points I am looking for are:
- Allow the Usage line to replicate a more traditional Unix/Linux help page
- Breaking down the options into separate categories based on whether they are required, optional, flags, etc.

**Comment by davidism** [comment] 2021-07-06 20:25
Duplicate of #561

**Closed by davidism** 2021-07-06 20:25 UTC
