### ISSUE TITLE
Support NO_COLOR environment variable

### ISSUE THREAD

**Issue by mmessmore** [pallets/click#2207] opened 2022-02-27 02:17 UTC
Support disabling color output globally using the NO_COLOR environment variable as specified here: https://no-color.org/

In particular it would be useful for CI output and users who dislike stylized output for my CLIs.

**Comment by davidism** [comment] 2022-02-27 13:42
Duplicate of #1498, although I _had_ been looking at this again recently. I'm open  to review a PR if you'd like to submit one.

**Comment by davidism** [comment] 2022-02-27 13:51
Duplicate of #1498. While I understand the intention of the proposal, it's not clear that it's the correct thing to do. For example, Click doesn't provide a `--color` option, so every project would still need to implement turning color _back on_ manually. At that point, why not also do this:

```python
if __name__ == "__main__":
    color = os.environ.get("NO_COLOR")
    color = color in {"1", "true"} if color is not None else None
    cli(color=color)
```

I did see that Rich implements this, but that alone isn't a convincing reason for it.

**Comment by mmessmore** [comment] 2022-02-27 14:55
Sorry, I should have found the prior issue. I’ll stare at the code more.

It really doesn’t need to be supported directly, I guess, but easy to implement support without logic around every style or secho. It may be already, so I’ll shut up now and actually read.  I don’t mean to ask you to spell it out for me.

To me, ideally there should be a simple pattern for support or direct support.

And I should not just whine but say “thank you”.  This library has made me happy and more productive for so long.

**Comment by davidism** [comment] 2022-02-27 15:18
No problem.

The color parameter shown above will tell Click to not output color codes. So if you want to support that env var, reading it and setting the parameter will do the right thing.

**Closed** 2022-04-28 16:45 UTC

**Comment by kdeldycke** [comment] 2022-04-29 17:56
If you're interested @mmessmore, I've created a [ready-to-use `--color/--no-color` flag option](https://github.com/kdeldycke/click-extra/blob/78b4f99bbd6c98cd979783ab88b6d80a16057daf/click_extra/colorize.py#L83-L180) for Click that is supporting the `NO_COLOR` convention. It is available as a part of [`click-extra`](https://github.com/kdeldycke/click-extra).

**Comment by mmessmore** [comment] 2022-04-30 01:16
Oh, thank you. That’s great.
