### ISSUE TITLE
Human readable name not used in parameter error messages

### ISSUE THREAD

**Issue by gar1t** [pallets/click#855] opened 2017-09-26 15:02 UTC
I'm getting error messages that look like this:

```
Usage: guild info [OPTIONS] PACKAGE
Try "guild info --help" for help.

Error: Missing argument "package".
```

IMO the last line should read `Missing argument PACKAGES` - "packages" is not reflected in the usage.

I believe the issue is here (and similar patterns in exceptions.py):

https://github.com/pallets/click/blob/master/click/exceptions.py#L121

where `self.param.opts` short-circuits the use of the human readable name, which would use metavar as expected.

**Comment by cdunklau** [comment] 2017-11-30 16:26
This looks like a dupe of #598

**Comment by LokiHokie** [comment] 2018-05-14 20:31
Fixed #709

**Closed by LokiHokie** 2018-05-14 20:31 UTC
