### ISSUE TITLE
Documenting a command's arguments needs clarification in docs

### ISSUE THREAD

**Issue by schollii** [pallets/click#1217] opened 2019-02-03 18:40 UTC
The documentation should explain why Argument does not have a help arg and how to do it instead. 

Indeed: Lots of people are unaware of the tacit convention that commands arguments should be referenced by name in the long help string of a command, instead of listed. I.e., whereas many CLI devs would naturally want help output of the form 
```
Usage: command .... ARG1 ARG2

  Do this and that, where:
  - ARG1: .....
  - ARG2: ....

Options: 
  ...
```
so they would expect each argument to have a help string, it appears the convention that Click wants to enforce is a help output like this: 
```
Usage: command .... ARG1 ARG2

  Do this with ARG1 and do that with ARG2 one paragraph without lists

Options: 
  ...
```

**Comment by davidism** [comment] 2019-02-03 19:58
https://click.palletsprojects.com/en/7.x/documentation/#help-texts

> Arguments cannot be documented this way. This is to follow the general convention of Unix tools of using arguments for only the most necessary things and to document them in the introduction text by referring to them by name.

https://click.palletsprojects.com/en/7.x/parameters/#differences

> options are fully documented in the help page, arguments are not (this is intentional as arguments might be too specific to be automatically documented)

https://click.palletsprojects.com/en/7.x/arguments/

> Click will also not attempt to document arguments for you and wants you to document them manually in order to avoid ugly help pages.

**Comment by davidism** [comment] 2019-02-03 19:59
Duplicate of #1051

**Closed by davidism** 2019-02-03 19:58 UTC

**Comment by schollii** [comment] 2019-02-03 20:40
OK sorry about that, had not noticed that, and thanks for quick reply.
