### ISSUE TITLE
Click website redirects to v5 documentation instead of v6 (latest stable).

### ISSUE THREAD

**Issue by mindw** [pallets/click#597] opened 2016-06-10 14:16 UTC

**Comment by glarrain** [comment] 2016-06-13 15:46
I noticed that too and was going to report it.

**Comment by iamthad** [comment] 2016-06-16 15:21
Some details:
A request to http://click.pocoo.org returns the following header:

    HTTP/1.1 302 Moved Temporarily
    Server: nginx
    Date: Thu, 16 Jun 2016 15:18:14 GMT
    Content-Type: text/html
    Content-Length: 154
    Location: http://click.pocoo.org/latest/
    Connection: keep-alive

Then, a request to http://click.pocoo.org/latest/ returns:

    HTTP/1.1 302 Moved Temporarily
    Server: nginx
    Date: Thu, 16 Jun 2016 15:20:33 GMT
    Content-Type: text/html
    Content-Length: 154
    Location: http://click.pocoo.org/5/
    Connection: keep-alive

So this is a server configuration issue, it appears.

**Comment by pietroalbini** [comment] 2016-06-17 11:33
[I guess it's intended behavior](https://github.com/pallets/click/issues/503#issuecomment-175140548).

**Comment by untitaker** [comment] 2016-09-05 18:14
Duplicate of https://github.com/pallets/click/issues/503

**Closed by untitaker** 2016-09-05 18:14 UTC
